// Generated by tools/generate_reference_allocation_profile.py.
// Identity metadata only; no original executable bodies are embedded.
// DOL SHA-1: 08e0bf20134dfcb260699671004527b2d6bb1a45
// Source revision: b43912cc78606f96c9569f5d6229bc9d7e265ea5
// Symbols SHA-256: 214477d5b27989a9675c4b881f4db2dad5eeaada39dbac17c57c70d5ba84d579
// Profile SHA-256: 30e6ccc981d5e8eea6d5c88381bfc3df5a3b1103599c2b632ddb48580165bf65
#pragma once
#include <array>
#include "Core/PowerPC/ReferenceAllocationObserver.h"
namespace ReferenceAllocation::Generated {
inline constexpr std::array<u32, 1> kReturns0 = {{0x80350f8cu}};
inline constexpr std::array<u32, 1> kReturns1 = {{0x80350e24u}};
inline constexpr std::array<u32, 1> kReturns2 = {{0x80350e98u}};
inline constexpr std::array<u32, 1> kReturns3 = {{0x80350f94u}};
inline constexpr std::array<u32, 1> kReturns4 = {{0x803440e4u}};
inline constexpr std::array<u32, 2> kReturns5 = {{0x8034413cu, 0x80344150u}};
inline constexpr std::array<u32, 1> kReturns6 = {{0x80344164u}};
inline constexpr std::array<u32, 1> kReturns7 = {{0x80344074u}};
inline constexpr std::array<u32, 2> kReturns8 = {{0x80343f30u, 0x80343fe8u}};
inline constexpr std::array<u32, 1> kReturns9 = {{0x80344064u}};
inline constexpr std::array<u32, 1> kReturns10 = {{0x803444e4u}};
inline constexpr std::array<u32, 1> kReturns11 = {{0x803444dcu}};
inline constexpr std::array<u32, 1> kReturns12 = {{0x80344510u}};
inline constexpr std::array<u32, 1> kReturns13 = {{0x80344530u}};
inline constexpr std::array<u32, 1> kReturns14 = {{0x80375400u}};
inline constexpr std::array<u32, 1> kReturns15 = {{0x80375190u}};
inline constexpr std::array<u32, 1> kReturns16 = {{0x80375254u}};
inline constexpr std::array<u32, 1> kReturns17 = {{0x8037552cu}};
inline constexpr std::array<u32, 1> kReturns18 = {{0x80375410u}};
inline constexpr std::array<u32, 1> kReturns19 = {{0x8037a964u}};
inline constexpr std::array<u32, 1> kReturns20 = {{0x8037ae24u}};
inline constexpr std::array<u32, 1> kReturns21 = {{0x8037abc4u}};
inline constexpr std::array<u32, 1> kReturns22 = {{0x8037ad1cu}};
inline constexpr std::array<u32, 1> kReturns23 = {{0x8037ad44u}};
inline constexpr std::array<u32, 1> kReturns24 = {{0x8037ae30u}};
inline constexpr std::array<u32, 1> kReturns25 = {{0x8037f240u}};
inline constexpr std::array<u32, 1> kReturns26 = {{0x8037f1e0u}};
inline constexpr std::array<u32, 1> kReturns27 = {{0x80016158u}};
inline constexpr std::array<u32, 1> kReturns28 = {{0x800158e4u}};
inline constexpr std::array<u32, 1> kReturns29 = {{0x80015bb4u}};
inline constexpr std::array<u32, 1> kReturns30 = {{0x80015ca4u}};
inline constexpr std::array<u32, 1> kReturns31 = {{0x80015d68u}};
inline constexpr std::array<u32, 1> kReturns32 = {{0x80015df4u}};
inline constexpr std::array<u32, 1> kReturns33 = {{0x800158ccu}};
inline constexpr std::array<u32, 1> kReturns34 = {{0x80014ee8u}};
inline constexpr std::array<u32, 1> kReturns35 = {{0x80014f78u}};
inline constexpr std::array<u32, 1> kReturns36 = {{0x800150ecu}};
inline constexpr std::array<u32, 1> kReturns37 = {{0x80015180u}};
inline constexpr std::array<u32, 1> kReturns38 = {{0x8001531cu}};
inline constexpr std::array<u32, 1> kReturns39 = {{0x800155a0u}};
inline constexpr std::array<u32, 1> kReturns40 = {{0x80015648u}};
inline constexpr std::array<u32, 1> kReturns41 = {{0x80067ab8u}};
inline constexpr std::array<u32, 1> kReturns42 = {{0x800693a8u}};
inline constexpr std::array<u32, 1> kReturns43 = {{0x8016e9c4u}};
inline constexpr std::array<u32, 1> kReturns44 = {{0x8016ebbcu}};
inline constexpr std::array<u32, 1> kReturns45 = {{0x80015298u}};
inline constexpr std::array<u32, 1> kReturns46 = {{0x800154b8u}};
inline constexpr std::array<u32, 1> kReturns47 = {{0x80017aacu}};
inline constexpr std::array<u32, 1> kReturns48 = {{0x8038ecd8u}};
inline constexpr std::array<u32, 1> kReturns49 = {{0x8038f950u}};
inline constexpr std::array<u32, 1> kReturns50 = {{0x800beb24u}};
inline constexpr std::array<u32, 1> kReturns51 = {{0x800beb5cu}};
inline constexpr std::array<FunctionIdentity, 52> kFunctions = { {
  {"ARInit", 0x80350e9cu, 0x000000f4u, 0x7c0802a6u, 2, kReturns0.data(), static_cast<u32>(kReturns0.size()), "7ff72977174513f962039820909640d9d5597ee148341d914808c6f1a51e7098"},
  {"ARAlloc", 0x80350dc0u, 0x00000068u, 0x7c0802a6u, 1, kReturns1.data(), static_cast<u32>(kReturns1.size()), "b146a5c6dc168e35495b1c58171801b991ba8797901c28ffd0aa0729db38e51f"},
  {"ARFree", 0x80350e28u, 0x00000074u, 0x7c0802a6u, 1, kReturns2.data(), static_cast<u32>(kReturns2.size()), "dc307f4b3db9f125c7e75d32d40145c210521b077a3a447282abb62d3eaa4251"},
  {"ARGetSize", 0x80350f90u, 0x00000008u, 0x806dbe14u, 0, kReturns3.data(), static_cast<u32>(kReturns3.size()), "7a98932271de068f3c5aa3e551edb36fa84c8bff908f7433c6e9bb62b2a7de86"},
  {"OSInitAlloc", 0x80344078u, 0x00000070u, 0x1ce5000cu, 3, kReturns4.data(), static_cast<u32>(kReturns4.size()), "6a569ed3582adfa427e03dea25ae0d59bd846b34f314466d28613cbcd31b6429"},
  {"OSCreateHeap", 0x803440e8u, 0x0000006cu, 0x80cdbcc4u, 2, kReturns5.data(), static_cast<u32>(kReturns5.size()), "11e3e9db1729991a4521c748235cfb8cbc4d7e1c7e7a5360ded628c6e588c659"},
  {"OSDestroyHeap", 0x80344154u, 0x00000014u, 0x1c03000cu, 1, kReturns6.data(), static_cast<u32>(kReturns6.size()), "6ce829d6afad6c57b6c198fa6dfb67372245efc0b29d077e5295bd14a8cce35e"},
  {"OSSetCurrentHeap", 0x80344068u, 0x00000010u, 0x800da568u, 1, kReturns7.data(), static_cast<u32>(kReturns7.size()), "0f12a0079afdead003a97b4714c6cb13aededb757cec40bdb471d8ec452023ed"},
  {"OSAllocFromHeap", 0x80343ef0u, 0x000000fcu, 0x1c03000cu, 2, kReturns8.data(), static_cast<u32>(kReturns8.size()), "01abece853a1c5bda0ccd50b452c501315b0ec18f2ccf05923d69cf620385363"},
  {"OSFreeToHeap", 0x80343fecu, 0x0000007cu, 0x7c0802a6u, 2, kReturns9.data(), static_cast<u32>(kReturns9.size()), "f9be87c5f059fe039b58ad994e76c10bb2ae8e98539bdc3bfbac8f409f27f825"},
  {"OSSetArenaLo", 0x803444e0u, 0x00000008u, 0x906da570u, 1, kReturns10.data(), static_cast<u32>(kReturns10.size()), "8e2be43a4e83171353c0df0867aa6abdf421847cd0f27e840b676592afec8466"},
  {"OSSetArenaHi", 0x803444d8u, 0x00000008u, 0x906dbcd0u, 1, kReturns11.data(), static_cast<u32>(kReturns11.size()), "805062cac8b9bef7b6f8e69fb1c4d6cf88ca93450683e56a986e0c8efceb7388"},
  {"OSAllocFromArenaLo", 0x803444e8u, 0x0000002cu, 0x800da570u, 2, kReturns12.data(), static_cast<u32>(kReturns12.size()), "e3cd2ff690341fe10d02fb1fe117a3f0319eb5b4a538dee822b8b86cb72cbe01"},
  {"OSAllocFromArenaHi", 0x80344514u, 0x00000020u, 0x3804ffffu, 2, kReturns13.data(), static_cast<u32>(kReturns13.size()), "c45f6ff698f5b1ef13c97dad666929bc0ece92f676c9c2670f915e69ec6c2e1f"},
  {"HSD_OSInit", 0x80375304u, 0x00000100u, 0x7c0802a6u, 0, kReturns14.data(), static_cast<u32>(kReturns14.size()), "33114e7aa17866795b82542335fc1250427c4c6db55ee6b144c7c3540ff0b76c"},
  {"HSD_AllocateXFB", 0x80374f7cu, 0x00000218u, 0x7c0802a6u, 2, kReturns15.data(), static_cast<u32>(kReturns15.size()), "1c48d343bc7b9479e14390430827df57fcea02f7279e07d3858ceb7d3bbd9eb0"},
  {"HSD_AllocateFifo", 0x80375194u, 0x000000c4u, 0x7c0802a6u, 1, kReturns16.data(), static_cast<u32>(kReturns16.size()), "b4d46346e8241da64f5213b06d4182b3b04010d73a3a857467fa7552efe364d3"},
  {"HSD_CreateMainHeap", 0x80375428u, 0x00000108u, 0x7c0802a6u, 2, kReturns17.data(), static_cast<u32>(kReturns17.size()), "8258cb8342efc4163cef196dd715a4dd0a76e440cfe17f5e4f8613db6a6ce8e2"},
  {"HSD_SetHeap", 0x8037540cu, 0x00000008u, 0x906da760u, 1, kReturns18.data(), static_cast<u32>(kReturns18.size()), "4e02ca0f7b2444a96f08878a21a2182af7ef2ef490f3cf50a3e2f31e7045641b"},
  {"HSD_ObjSetHeap", 0x8037a94cu, 0x0000001cu, 0x3ca08040u, 2, kReturns19.data(), static_cast<u32>(kReturns19.size()), "947d48f4782251f5fea5cb27dd46951d2ae0f70d1660f3741d66d314e527bca1"},
  {"HSD_ObjAllocInit", 0x8037ad48u, 0x000000e0u, 0x7c0802a6u, 3, kReturns20.data(), static_cast<u32>(kReturns20.size()), "bc17658e83ac6d0a7c5e1cba8cdf8b7b50f029d6b2f38a32ebbb72dcc35d45bb"},
  {"HSD_ObjAllocAddFree", 0x8037a968u, 0x00000260u, 0x7c0802a6u, 2, kReturns21.data(), static_cast<u32>(kReturns21.size()), "d4bbb33a19c958493157d896cd765d3ebdf268c9c07384b69bf2e3909c6b3fac"},
  {"HSD_ObjAlloc", 0x8037abc8u, 0x00000158u, 0x7c0802a6u, 1, kReturns22.data(), static_cast<u32>(kReturns22.size()), "7422873421e8599ea17bd934e3b71146f56fd6bb8056451bba3a8080faa1d487"},
  {"HSD_ObjFree", 0x8037ad20u, 0x00000028u, 0x80030004u, 2, kReturns23.data(), static_cast<u32>(kReturns23.size()), "c5ff617e3a9529eddb1dcddee69be9afa5d85e888615ea7e7069f410b6827211"},
  {"_HSD_ObjAllocForgetMemory", 0x8037ae28u, 0x0000000cu, 0x38000000u, 2, kReturns24.data(), static_cast<u32>(kReturns24.size()), "ec99b54c4fbf0744903e4cda5902f7689883faec33ac962d584a43f86d34b997"},
  {"HSD_MemAlloc", 0x8037f1e4u, 0x00000060u, 0x7c0802a6u, 1, kReturns25.data(), static_cast<u32>(kReturns25.size()), "ad3bc91d628f6292e957c269902b5ddc2dc6a4cb339e1bdbb5e84aae9b1bc0c5"},
  {"HSD_Free", 0x8037f1b0u, 0x00000034u, 0x7c0802a6u, 1, kReturns26.data(), static_cast<u32>(kReturns26.size()), "334bbd64e342c57116c8528f3892f3368b338135de0ac0ab38dd4e58649531ea"},
  {"lbHeap_80015F3C", 0x80015f3cu, 0x00000220u, 0x7c0802a6u, 0, kReturns27.data(), static_cast<u32>(kReturns27.size()), "841273b4b2af5db3ed0e91a7d6be403e1a8f09d08c698a8c947a41523595941e"},
  {"lbHeap_800158D0", 0x800158d0u, 0x00000018u, 0x1c03001cu, 2, kReturns28.data(), static_cast<u32>(kReturns28.size()), "929693c0c54c483b8c724c4ca672bdb63e717a2a3752c29b7d92cb438679b480"},
  {"lbHeap_80015900", 0x80015900u, 0x000002b8u, 0x7c0802a6u, 0, kReturns29.data(), static_cast<u32>(kReturns29.size()), "a8eaec52c438bf8b816a3a0642fa830c966f4067be0f537ecda93959a8b6fe26"},
  {"lbHeap_80015BD0", 0x80015bd0u, 0x000000d8u, 0x7c0802a6u, 2, kReturns30.data(), static_cast<u32>(kReturns30.size()), "a7b8ef3b99e4bccc13a7ae1a2626138fecc966b8f1949ad0928a5436edf32ba0"},
  {"lbHeap_80015CA8", 0x80015ca8u, 0x000000c4u, 0x7c0802a6u, 2, kReturns31.data(), static_cast<u32>(kReturns31.size()), "0d9af610e46cfbf709fc199c7c4258de158345f905c9da27742356616d6fc922"},
  {"lbHeap_80015D6C", 0x80015d6cu, 0x0000008cu, 0x7c0802a6u, 3, kReturns32.data(), static_cast<u32>(kReturns32.size()), "1f196f924c844122b178705e57ef0a634e8c27561fdf1a373c8edf64697ef680"},
  {"lbMemory_8001564C", 0x8001564cu, 0x00000284u, 0x7c0802a6u, 0, kReturns33.data(), static_cast<u32>(kReturns33.size()), "18f80cce492032b78d8b95f74a3ada563562a9689e01821e33c96ca5259d1d47"},
  {"lbMemory_80014E24", 0x80014e24u, 0x000000c8u, 0x7c0802a6u, 2, kReturns34.data(), static_cast<u32>(kReturns34.size()), "b3490634eb4263279abd6891f0584904455049af052732cc26c6eeaef82abf9d"},
  {"lbMemory_80014EEC", 0x80014eecu, 0x00000090u, 0x7c0802a6u, 1, kReturns35.data(), static_cast<u32>(kReturns35.size()), "0ce7017cbf7956f1faf8e98cce9be2b517b0b8531e308ab9a860db09927e98c5"},
  {"lbMemory_80014FC8", 0x80014fc8u, 0x00000128u, 0x7c0802a6u, 2, kReturns36.data(), static_cast<u32>(kReturns36.size()), "b9e556bf194fa1f156763255cd34980d5a2d642d46e0799e1bda1c0cac7663a5"},
  {"lbMemFreeToHeap", 0x800150f0u, 0x00000094u, 0x7c0802a6u, 2, kReturns37.data(), static_cast<u32>(kReturns37.size()), "27c1d6e3b84f39c26ae2bb726442ad62aed0d604c28f99b1d277d54e23dc8fe0"},
  {"lbMemory_8001529C", 0x8001529cu, 0x00000084u, 0x7c0802a6u, 3, kReturns38.data(), static_cast<u32>(kReturns38.size()), "0f9ab7b2d6c27973a5f76a952f6678847ab9fe85f505f0ac045309ebf54218e8"},
  {"lbMemory_800154D4", 0x800154d4u, 0x000000d0u, 0x7c0802a6u, 2, kReturns39.data(), static_cast<u32>(kReturns39.size()), "ec77858ddcf764df741b466e008f16278529096d34bf1bea8a87f0016c391e74"},
  {"lbMemory_800155A4", 0x800155a4u, 0x000000a8u, 0x7c0802a6u, 0, kReturns40.data(), static_cast<u32>(kReturns40.size()), "59d11342a88492698da4693d83fb1d12781c4a242e8deebd745e5c9450e605ae"},
  {"Fighter_FirstInitialize_80067A84", 0x80067a84u, 0x00000038u, 0x7c0802a6u, 0, kReturns41.data(), static_cast<u32>(kReturns41.size()), "fb9f32b1e632d9576937bf44e4281ef1ae5f116338e961c7cc7437fe47476a51"},
  {"Fighter_Create", 0x80068e98u, 0x00000514u, 0x7c0802a6u, 1, kReturns42.data(), static_cast<u32>(kReturns42.size()), "f50b9d1de0aa4be8369fabfbf6c488c9f31a5e0abbb9046cad1b01e5d74bd448"},
  {"gm_Scene_Vs_OnEnter", 0x8016e934u, 0x00000094u, 0x7c0802a6u, 1, kReturns43.data(), static_cast<u32>(kReturns43.size()), "5243c130467b4409ec38235e0487329dde795fe21cea8ce94612f7522f4dd940"},
  {"gm_Scene_Vs_OnExit", 0x8016e9c8u, 0x000001f8u, 0x7c0802a6u, 1, kReturns44.data(), static_cast<u32>(kReturns44.size()), "b5bc15da8b120443b35036d6d49b7249119d517a09e7974accd28fc871919ce3"},
  {"fn_80015184", 0x80015184u, 0x00000118u, 0x7c0802a6u, 2, kReturns45.data(), static_cast<u32>(kReturns45.size()), "f3b53d6a64562a5d80308b831dcab56b933cd266fa6b94b9aab90f127c195774"},
  {"lbMemory_80015320", 0x80015320u, 0x0000019cu, 0x7c0802a6u, 4, kReturns46.data(), static_cast<u32>(kReturns46.size()), "cc99f2b34697144fdf29ca43f26642406e8c154b6d312b9246ce28fde595cd4d"},
  {"lbDvd_80017A80", 0x80017a80u, 0x00000030u, 0x7c0802a6u, 1, kReturns47.data(), static_cast<u32>(kReturns47.size()), "9dd8e2c8ff8af3a65a6d4ebff1da716825954918a011d6f7981ed22cb2d91cc6"},
  {"HSD_DevComARAMCallback", 0x8038ebccu, 0x00000110u, 0x7c0802a6u, 1, kReturns48.data(), static_cast<u32>(kReturns48.size()), "e537a493a3669043a944b6902da13395be397187d0c4e7ea96ecda7b17c1f1ea"},
  {"HSD_DevComRequest", 0x8038f6d4u, 0x00000280u, 0x7c0802a6u, 8, kReturns49.data(), static_cast<u32>(kReturns49.size()), "219bba0d0b6aede387879888140d014f207907ac5d77b76dc0be792b0b166d77"},
  {"ftDemo_CreateFighter", 0x800be7e0u, 0x00000348u, 0x7c0802a6u, 1, kReturns50.data(), static_cast<u32>(kReturns50.size()), "530be329d151e5262f62f2cca83294c6d1c40dc7d495afdb0d7fe91679c38573"},
  {"ftDemo_ObjAllocInit", 0x800beb28u, 0x00000038u, 0x7c0802a6u, 0, kReturns51.data(), static_cast<u32>(kReturns51.size()), "4894716d0946d2d46d760f552fb6b8cea3ec63ffef115e4c0dee9dcfbd9c94fa"},
}};
inline constexpr std::array<GlobalIdentity, 23> kGlobals = { {
  {"HeapArray", 0x804d7360u, 0x00000004u},
  {"NumHeaps", 0x804d7364u, 0x00000004u},
  {"ArenaStart", 0x804d7368u, 0x00000004u},
  {"ArenaEnd", 0x804d736cu, 0x00000004u},
  {"__OSArenaLo", 0x804d5c10u, 0x00000004u},
  {"__OSArenaHi", 0x804d7370u, 0x00000004u},
  {"seed", 0x804d5f90u, 0x00000004u},
  {"seed_ptr", 0x804d5f94u, 0x00000004u},
  {"fighter_alloc_data", 0x80458fd0u, 0x0000002cu},
  {"obj_heap", 0x80406e48u, 0x00000010u},
  {"current_heap", 0x804d5e00u, 0x00000004u},
  {"__OSCurrHeap", 0x804d5c08u, 0x00000004u},
  {"lbHeap_80431FA0", 0x80431fa0u, 0x000000b8u},
  {"lbMemory_804318B0", 0x804318b0u, 0x000006f0u},
  {"iparam_audio_heap_size", 0x804d5e18u, 0x00000004u},
  {"iparam_heap_max_num", 0x804d5e14u, 0x00000004u},
  {"hsd_heap_next_arena_lo", 0x804d76b8u, 0x00000004u},
  {"hsd_heap_next_arena_hi", 0x804d76bcu, 0x00000004u},
  {"__AR_Size", 0x804d74b4u, 0x00000004u},
  {"__AR_StackPointer", 0x804d74b8u, 0x00000004u},
  {"__AR_FreeBlocks", 0x804d74bcu, 0x00000004u},
  {"__AR_BlockLength", 0x804d74c0u, 0x00000004u},
  {"__AR_init_flag", 0x804d74c4u, 0x00000004u},
}};
inline const BoundProfile kProfile{
  "08e0bf20134dfcb260699671004527b2d6bb1a45",
  "b43912cc78606f96c9569f5d6229bc9d7e265ea5",
  "30e6ccc981d5e8eea6d5c88381bfc3df5a3b1103599c2b632ddb48580165bf65",
  0x8000522cu,
  0x48000115u,
  kFunctions.data(), static_cast<u32>(kFunctions.size()),
  kGlobals.data(), static_cast<u32>(kGlobals.size()), true,
};
}  // namespace ReferenceAllocation::Generated
