// Generated by scripts/generate_common_schema.py. Do not edit.
// Source SHA-256: 3eed871742686e0f44aaee7cc83866546bdfc3b8ea65c6632167e1cd7eb76e9c
// x808 uses its sequential C layout; the pinned +804 comment is a known typo.
#ifndef MELEE_WEB_COMMON_SCHEMA_H
#define MELEE_WEB_COMMON_SCHEMA_H
#include <stdint.h>
#include <stddef.h>
#define MELEE_WEB_COMMON_SCALAR_BYTES 0x818u
#define MELEE_WEB_COMMON_ROOT_COUNT 23u
typedef struct MeleeWebCommonVec2 {
    float x;
    float y;
} MeleeWebCommonVec2;
typedef struct MeleeWebCommonVec3 {
    float x;
    float y;
    float z;
} MeleeWebCommonVec3;
typedef struct MeleeWebCommonColor {
    uint8_t r;
    uint8_t g;
    uint8_t b;
    uint8_t a;
} MeleeWebCommonColor;
typedef struct MeleeWebCommonHitbox {
    int32_t state;
    uint32_t damage;
    int32_t kb_angle;
    uint32_t unkC;
    uint32_t unk10;
    uint32_t unk14;
    uint32_t element;
    int32_t sfx_severity;
    int32_t sfx_kind;
} MeleeWebCommonHitbox;
// UNK_T source placeholders are opaque 32-bit scalar words, never host addresses.
typedef struct MeleeWebCommonScalars {
    float horizontal_stick_deadzone;
    float vertical_stick_deadzone;
    float horizontal_stick_smash_deadzone;
    float vertical_stick_smash_deadzone;
    float analog_shoulder_deadzone;
    float z_press_analog_value;
    float shield_press_threshold;
    int32_t x1C;
    float x20_radians;
    float walk_stick_threshold;
    float walk_middle_animation_stick_threshold;
    float walk_fast_stick_threshold;
    float walk_accel_taper_gain;
    float x34;
    float x38_someLStickXThreshold;
    float dash_smash_stick_threshold;
    int32_t dash_smash_window;
    float x44;
    float x48;
    float x4C;
    float x50;
    float x54;
    float x58_someLStickXThreshold;
    float run_accel_taper_gain;
    float run_dash_turn_friction_multiplier;
    float x64;
    float x68;
    float friction_when_above_walk_speed;
    float tap_jump_threshold;
    int32_t tap_jump_window;
    float x78;
    float tap_jump_release_threshold;
    float relaxed_tap_jump_threshold;
    float x84;
    float x88;
    int32_t x8C;
    float x90;
    float x94;
    float x98;
    float x9C_radians;
    float xA0_radians;
    float xA4_radians;
    float xA8_radians;
    float attackhi3_stick_threshold_y;
    float xB0;
    float xB4;
    float xB8_radians;
    float xBC_radians;
    float xC0_radians;
    float xC4_radians;
    float xC8;
    float xCC;
    float xD0;
    float xD4;
    float xD8;
    float xDC;
    float xE0;
    int32_t xE4;
    float xE8;
    float xEC;
    float xF0;
    float xF4;
    float xF8;
    int32_t xFC;
    float x100;
    float kb_min;
    float x108;
    float x10C;
    float x110;
    float x114;
    float x118;
    float x11C;
    float x120;
    float kb_squat_mul;
    float x128;
    float x12C;
    int32_t x130;
    int32_t x134;
    float x138;
    float x13C;
    float x140;
    float x144_radians;
    float x148;
    float x14C;
    float x150;
    float x154;
    float x158;
    float x15C;
    float x160;
    float x164;
    float x168;
    float x16C;
    float x170;
    float x174;
    float x178;
    float x17C;
    float x180;
    float x184;
    float x188;
    int32_t x18C;
    float x190;
    float x194_unkHitLagFrames;
    float x198;
    float x19C;
    float x1A0;
    float x1A4;
    float x1A8;
    float x1AC;
    float x1B0;
    float x1B4;
    int32_t x1B8;
    float x1BC;
    float x1C0;
    float x1C4;
    float x1C8;
    float x1CC;
    float x1D0;
    float x1D4;
    float x1D8;
    uint32_t x1DC;
    float x1E0;
    float x1E4;
    float x1E8_radians;
    float x1EC;
    float x1F0;
    float x1F4;
    float x1F8;
    float x1FC;
    float x200;
    float x204_knockbackFrameDecay;
    float x208;
    float x20C;
    float x210;
    int32_t x214;
    float x218;
    float x21C;
    float x220;
    int32_t x224;
    float x228;
    float x22C;
    float x230;
    float x234_radians;
    float x238_radians;
    uint32_t x23C;
    float x240;
    float x244;
    float x248;
    float x24C;
    float x250;
    float x254;
    float x258;
    float x25C;
    float x260_startShieldHealth;
    float x264;
    float x268;
    float x26C;
    float x270;
    uint32_t x274;
    float x278;
    float x27C;
    float x280_unkShieldHealth;
    float x284;
    float x288;
    float x28C;
    float x290;
    float x294;
    float x298;
    float x29C;
    int32_t powershield_input_window;
    float x2A4;
    float x2A8;
    float x2AC;
    float x2B0;
    float x2B4;
    int32_t x2B8;
    float x2BC;
    float x2C0;
    float x2C4;
    float x2C8;
    float x2CC;
    float x2D0;
    float x2D4;
    float x2D8;
    float x2DC;
    float x2E0;
    float x2E4;
    float x2E8;
    float x2EC;
    float x2F0;
    float x2F4;
    float x2F8;
    float x2FC;
    float x300;
    float x304;
    float x308;
    float x30C;
    float x310;
    float x314;
    int32_t x318;
    float x31C;
    int32_t x320;
    int32_t x324;
    float x328;
    MeleeWebCommonVec2 escapeair_deadzone;
    int32_t x334;
    float escapeair_force;
    float escapeair_decay;
    float x340;
    float x344;
    int32_t x348;
    float x34C;
    float x350;
    float x354;
    float x358;
    float x35C;
    float x360;
    float x364;
    float x368;
    float x36C;
    float x370;
    float x374;
    float x378;
    float x37C;
    MeleeWebCommonHitbox x380;
    float grab_timer_decrement;
    float x3A8;
    float x3AC;
    float x3B0;
    float shouldered_anim_rate;
    float x3B8;
    float x3BC;
    int32_t x3C0;
    float x3C4;
    float x3C8;
    int32_t x3CC;
    float x3D0;
    float x3D4;
    float x3D8;
    float x3DC;
    float x3E0;
    float x3E4;
    float x3E8_shieldKnockbackFrameDecay;
    float x3EC_shieldGroundFrictionMultiplier;
    float x3F0;
    uint32_t x3F4;
    uint32_t x3F8;
    int32_t x3FC;
    float x400;
    float x404;
    float x408;
    float x40C;
    int32_t x410;
    int32_t x414;
    int32_t x418;
    int32_t x41C;
    float x420;
    float x424;
    int32_t x428;
    float x42C;
    float x430;
    float x434;
    float x438;
    float x43C;
    float x440;
    float x444;
    float x448;
    float x44C;
    float x450;
    float x454;
    float x458;
    float x45C;
    float x460;
    float x464;
    float x468;
    float x46C;
    float x470;
    float teeter_walk_threshold;
    float x478;
    float x47C;
    float x480;
    float x484;
    int32_t x488;
    float x48C;
    float x490;
    float x494;
    int32_t ledge_cooldown;
    int32_t x49C;
    float x4A0;
    float x4A4;
    float x4A8;
    float x4AC;
    float sdi_min_stick_mag;
    int32_t sdi_stick_window;
    float sdi_pos_scale;
    float x4BC;
    float x4C0;
    int32_t x4C4;
    int32_t x4C8;
    int32_t x4CC;
    float x4D0;
    float x4D4;
    uint32_t x4D8;
    MeleeWebCommonVec2 x4DC;
    MeleeWebCommonVec3 x4E4;
    float x4F0;
    float x4F4;
    uint32_t x4F8;
    uint32_t x4FC;
    uint32_t x500;
    int32_t x504;
    uint32_t x508;
    uint32_t x50C;
    float x510;
    float x514;
    uint32_t x518;
    float x51C_radians;
    int32_t x520;
    uint32_t x524;
    uint32_t x528;
    uint32_t x52C;
    uint32_t x530;
    uint32_t x534;
    uint32_t x538;
    float x53C;
    float x540;
    uint32_t x544;
    float x548;
    float x54C;
    float x550;
    float x554;
    float x558;
    float x55C;
    float x560_radians;
    float x564;
    float x568;
    float x56C;
    float x570;
    float x574;
    float x578;
    int32_t x57C;
    int32_t x580;
    int32_t x584;
    int32_t x588;
    float x58C;
    float x590;
    float open_parasol_threshold;
    float close_parasol_threshold;
    float x59C;
    float x5A0;
    int32_t x5A4;
    float x5A8;
    float x5AC;
    float x5B0;
    int32_t x5B4;
    float x5B8;
    uint32_t x5BC;
    float x5C0;
    uint32_t x5C4;
    int32_t x5C8;
    float x5CC;
    uint32_t x5D0;
    uint32_t x5D4;
    int32_t x5D8;
    uint32_t bury_timer_unk1;
    uint32_t bury_timer_unk2;
    uint32_t bury_timer_unk3;
    float x5E8;
    uint32_t x5EC;
    uint32_t x5F0;
    int32_t x5F4;
    float x5F8;
    float x5FC;
    float x600;
    float x604;
    float x608;
    float x60C;
    float x610;
    float x614;
    float x618;
    float x61C;
    int32_t x620;
    float x624;
    float x628;
    float x62C;
    float x630;
    float x634;
    float x638;
    float x63C;
    float x640;
    float x644;
    int32_t x648;
    float x64C;
    float x650;
    float x654;
    float x658;
    float x65C;
    float x660;
    float x664;
    float pressed_inputs;
    float released_inputs;
    float x670;
    float x674;
    float x678;
    float x67C;
    float x680;
    float x684;
    int32_t x688;
    int32_t x68C;
    int32_t x690;
    float x694;
    float x698;
    float warpstarfall_drift_scaling;
    float warpstarfall_drift_flat;
    float warpstarfall_drift_max;
    float x6A8;
    int32_t x6AC;
    int32_t x6B0;
    int32_t x6B4;
    int32_t x6B8;
    int32_t x6BC;
    int32_t x6C0;
    float x6C4;
    int32_t x6C8;
    int32_t x6CC;
    float x6D0;
    int32_t x6D4;
    int32_t x6D8[1];
    MeleeWebCommonColor x6DC_colorsByPlayer[4];
    uint8_t x6EC[4];
    float metal_armor;
    int32_t x6F4_unkDamage;
    int32_t x6F8;
    int32_t x6FC;
    int32_t x700;
    float x704;
    float x708;
    float x70C;
    float x710;
    float x714;
    float kb_ice_mul;
    float x71C;
    float x720;
    float x724;
    float x728;
    float x72C;
    float x730;
    float leadead_grab_timer_step;
    float leadead_grab_break_threshold;
    int32_t x73C;
    float x740;
    float x744;
    float x748;
    float x74C;
    float x750;
    float x754;
    float x758;
    float x75C;
    int32_t x760;
    int32_t x764;
    float x768;
    float x76C;
    float x770;
    int32_t x774;
    float passive_wall_vel_y_base;
    float damageice_gravity_mult;
    float damageice_min_speed;
    float damageice_speed_mult_on_break;
    float damageice_rot_speed_min;
    float damageice_rot_speed_max;
    float x790_damageice_unk;
    float x794_damageice_unk;
    float x798_damageice_unk;
    float damageice_dmg_time_reduction_mult;
    float damageice_ice_size;
    float damageicejump_escape_time;
    float x7A8;
    int32_t x7AC;
    int32_t x7B0;
    int32_t x7B4_unkDamage;
    float x7B8;
    float x7BC;
    float x7C0;
    float kb_smashcharge_mul;
    float x7C8;
    int32_t x7CC;
    int32_t x7D0;
    float hit_weight_mul;
    MeleeWebCommonColor x7D8;
    int32_t x7DC;
    int32_t x7E0;
    float x7E4_scaleZ;
    uint32_t unk_kb_angle_min;
    uint32_t unk_kb_angle_max;
    int32_t x7F0;
    float x7F4;
    float x7F8;
    float x7FC;
    float x800;
    float x804;
    MeleeWebCommonVec3 x808;
    int32_t x814;
} MeleeWebCommonScalars;

#define MELEE_WEB_COMMON_FIELDS(X) \
    X(0x000, F32, horizontal_stick_deadzone) \
    X(0x004, F32, vertical_stick_deadzone) \
    X(0x008, F32, horizontal_stick_smash_deadzone) \
    X(0x00c, F32, vertical_stick_smash_deadzone) \
    X(0x010, F32, analog_shoulder_deadzone) \
    X(0x014, F32, z_press_analog_value) \
    X(0x018, F32, shield_press_threshold) \
    X(0x01c, I32, x1C) \
    X(0x020, F32, x20_radians) \
    X(0x024, F32, walk_stick_threshold) \
    X(0x028, F32, walk_middle_animation_stick_threshold) \
    X(0x02c, F32, walk_fast_stick_threshold) \
    X(0x030, F32, walk_accel_taper_gain) \
    X(0x034, F32, x34) \
    X(0x038, F32, x38_someLStickXThreshold) \
    X(0x03c, F32, dash_smash_stick_threshold) \
    X(0x040, I32, dash_smash_window) \
    X(0x044, F32, x44) \
    X(0x048, F32, x48) \
    X(0x04c, F32, x4C) \
    X(0x050, F32, x50) \
    X(0x054, F32, x54) \
    X(0x058, F32, x58_someLStickXThreshold) \
    X(0x05c, F32, run_accel_taper_gain) \
    X(0x060, F32, run_dash_turn_friction_multiplier) \
    X(0x064, F32, x64) \
    X(0x068, F32, x68) \
    X(0x06c, F32, friction_when_above_walk_speed) \
    X(0x070, F32, tap_jump_threshold) \
    X(0x074, I32, tap_jump_window) \
    X(0x078, F32, x78) \
    X(0x07c, F32, tap_jump_release_threshold) \
    X(0x080, F32, relaxed_tap_jump_threshold) \
    X(0x084, F32, x84) \
    X(0x088, F32, x88) \
    X(0x08c, I32, x8C) \
    X(0x090, F32, x90) \
    X(0x094, F32, x94) \
    X(0x098, F32, x98) \
    X(0x09c, F32, x9C_radians) \
    X(0x0a0, F32, xA0_radians) \
    X(0x0a4, F32, xA4_radians) \
    X(0x0a8, F32, xA8_radians) \
    X(0x0ac, F32, attackhi3_stick_threshold_y) \
    X(0x0b0, F32, xB0) \
    X(0x0b4, F32, xB4) \
    X(0x0b8, F32, xB8_radians) \
    X(0x0bc, F32, xBC_radians) \
    X(0x0c0, F32, xC0_radians) \
    X(0x0c4, F32, xC4_radians) \
    X(0x0c8, F32, xC8) \
    X(0x0cc, F32, xCC) \
    X(0x0d0, F32, xD0) \
    X(0x0d4, F32, xD4) \
    X(0x0d8, F32, xD8) \
    X(0x0dc, F32, xDC) \
    X(0x0e0, F32, xE0) \
    X(0x0e4, I32, xE4) \
    X(0x0e8, F32, xE8) \
    X(0x0ec, F32, xEC) \
    X(0x0f0, F32, xF0) \
    X(0x0f4, F32, xF4) \
    X(0x0f8, F32, xF8) \
    X(0x0fc, I32, xFC) \
    X(0x100, F32, x100) \
    X(0x104, F32, kb_min) \
    X(0x108, F32, x108) \
    X(0x10c, F32, x10C) \
    X(0x110, F32, x110) \
    X(0x114, F32, x114) \
    X(0x118, F32, x118) \
    X(0x11c, F32, x11C) \
    X(0x120, F32, x120) \
    X(0x124, F32, kb_squat_mul) \
    X(0x128, F32, x128) \
    X(0x12c, F32, x12C) \
    X(0x130, I32, x130) \
    X(0x134, I32, x134) \
    X(0x138, F32, x138) \
    X(0x13c, F32, x13C) \
    X(0x140, F32, x140) \
    X(0x144, F32, x144_radians) \
    X(0x148, F32, x148) \
    X(0x14c, F32, x14C) \
    X(0x150, F32, x150) \
    X(0x154, F32, x154) \
    X(0x158, F32, x158) \
    X(0x15c, F32, x15C) \
    X(0x160, F32, x160) \
    X(0x164, F32, x164) \
    X(0x168, F32, x168) \
    X(0x16c, F32, x16C) \
    X(0x170, F32, x170) \
    X(0x174, F32, x174) \
    X(0x178, F32, x178) \
    X(0x17c, F32, x17C) \
    X(0x180, F32, x180) \
    X(0x184, F32, x184) \
    X(0x188, F32, x188) \
    X(0x18c, I32, x18C) \
    X(0x190, F32, x190) \
    X(0x194, F32, x194_unkHitLagFrames) \
    X(0x198, F32, x198) \
    X(0x19c, F32, x19C) \
    X(0x1a0, F32, x1A0) \
    X(0x1a4, F32, x1A4) \
    X(0x1a8, F32, x1A8) \
    X(0x1ac, F32, x1AC) \
    X(0x1b0, F32, x1B0) \
    X(0x1b4, F32, x1B4) \
    X(0x1b8, I32, x1B8) \
    X(0x1bc, F32, x1BC) \
    X(0x1c0, F32, x1C0) \
    X(0x1c4, F32, x1C4) \
    X(0x1c8, F32, x1C8) \
    X(0x1cc, F32, x1CC) \
    X(0x1d0, F32, x1D0) \
    X(0x1d4, F32, x1D4) \
    X(0x1d8, F32, x1D8) \
    X(0x1dc, OPAQUE32, x1DC) \
    X(0x1e0, F32, x1E0) \
    X(0x1e4, F32, x1E4) \
    X(0x1e8, F32, x1E8_radians) \
    X(0x1ec, F32, x1EC) \
    X(0x1f0, F32, x1F0) \
    X(0x1f4, F32, x1F4) \
    X(0x1f8, F32, x1F8) \
    X(0x1fc, F32, x1FC) \
    X(0x200, F32, x200) \
    X(0x204, F32, x204_knockbackFrameDecay) \
    X(0x208, F32, x208) \
    X(0x20c, F32, x20C) \
    X(0x210, F32, x210) \
    X(0x214, I32, x214) \
    X(0x218, F32, x218) \
    X(0x21c, F32, x21C) \
    X(0x220, F32, x220) \
    X(0x224, I32, x224) \
    X(0x228, F32, x228) \
    X(0x22c, F32, x22C) \
    X(0x230, F32, x230) \
    X(0x234, F32, x234_radians) \
    X(0x238, F32, x238_radians) \
    X(0x23c, OPAQUE32, x23C) \
    X(0x240, F32, x240) \
    X(0x244, F32, x244) \
    X(0x248, F32, x248) \
    X(0x24c, F32, x24C) \
    X(0x250, F32, x250) \
    X(0x254, F32, x254) \
    X(0x258, F32, x258) \
    X(0x25c, F32, x25C) \
    X(0x260, F32, x260_startShieldHealth) \
    X(0x264, F32, x264) \
    X(0x268, F32, x268) \
    X(0x26c, F32, x26C) \
    X(0x270, F32, x270) \
    X(0x274, OPAQUE32, x274) \
    X(0x278, F32, x278) \
    X(0x27c, F32, x27C) \
    X(0x280, F32, x280_unkShieldHealth) \
    X(0x284, F32, x284) \
    X(0x288, F32, x288) \
    X(0x28c, F32, x28C) \
    X(0x290, F32, x290) \
    X(0x294, F32, x294) \
    X(0x298, F32, x298) \
    X(0x29c, F32, x29C) \
    X(0x2a0, I32, powershield_input_window) \
    X(0x2a4, F32, x2A4) \
    X(0x2a8, F32, x2A8) \
    X(0x2ac, F32, x2AC) \
    X(0x2b0, F32, x2B0) \
    X(0x2b4, F32, x2B4) \
    X(0x2b8, I32, x2B8) \
    X(0x2bc, F32, x2BC) \
    X(0x2c0, F32, x2C0) \
    X(0x2c4, F32, x2C4) \
    X(0x2c8, F32, x2C8) \
    X(0x2cc, F32, x2CC) \
    X(0x2d0, F32, x2D0) \
    X(0x2d4, F32, x2D4) \
    X(0x2d8, F32, x2D8) \
    X(0x2dc, F32, x2DC) \
    X(0x2e0, F32, x2E0) \
    X(0x2e4, F32, x2E4) \
    X(0x2e8, F32, x2E8) \
    X(0x2ec, F32, x2EC) \
    X(0x2f0, F32, x2F0) \
    X(0x2f4, F32, x2F4) \
    X(0x2f8, F32, x2F8) \
    X(0x2fc, F32, x2FC) \
    X(0x300, F32, x300) \
    X(0x304, F32, x304) \
    X(0x308, F32, x308) \
    X(0x30c, F32, x30C) \
    X(0x310, F32, x310) \
    X(0x314, F32, x314) \
    X(0x318, I32, x318) \
    X(0x31c, F32, x31C) \
    X(0x320, I32, x320) \
    X(0x324, I32, x324) \
    X(0x328, F32, x328) \
    X(0x32c, F32, escapeair_deadzone.x) \
    X(0x330, F32, escapeair_deadzone.y) \
    X(0x334, I32, x334) \
    X(0x338, F32, escapeair_force) \
    X(0x33c, F32, escapeair_decay) \
    X(0x340, F32, x340) \
    X(0x344, F32, x344) \
    X(0x348, I32, x348) \
    X(0x34c, F32, x34C) \
    X(0x350, F32, x350) \
    X(0x354, F32, x354) \
    X(0x358, F32, x358) \
    X(0x35c, F32, x35C) \
    X(0x360, F32, x360) \
    X(0x364, F32, x364) \
    X(0x368, F32, x368) \
    X(0x36c, F32, x36C) \
    X(0x370, F32, x370) \
    X(0x374, F32, x374) \
    X(0x378, F32, x378) \
    X(0x37c, F32, x37C) \
    X(0x380, I32, x380.state) \
    X(0x384, U32, x380.damage) \
    X(0x388, I32, x380.kb_angle) \
    X(0x38c, U32, x380.unkC) \
    X(0x390, U32, x380.unk10) \
    X(0x394, U32, x380.unk14) \
    X(0x398, U32, x380.element) \
    X(0x39c, I32, x380.sfx_severity) \
    X(0x3a0, I32, x380.sfx_kind) \
    X(0x3a4, F32, grab_timer_decrement) \
    X(0x3a8, F32, x3A8) \
    X(0x3ac, F32, x3AC) \
    X(0x3b0, F32, x3B0) \
    X(0x3b4, F32, shouldered_anim_rate) \
    X(0x3b8, F32, x3B8) \
    X(0x3bc, F32, x3BC) \
    X(0x3c0, I32, x3C0) \
    X(0x3c4, F32, x3C4) \
    X(0x3c8, F32, x3C8) \
    X(0x3cc, I32, x3CC) \
    X(0x3d0, F32, x3D0) \
    X(0x3d4, F32, x3D4) \
    X(0x3d8, F32, x3D8) \
    X(0x3dc, F32, x3DC) \
    X(0x3e0, F32, x3E0) \
    X(0x3e4, F32, x3E4) \
    X(0x3e8, F32, x3E8_shieldKnockbackFrameDecay) \
    X(0x3ec, F32, x3EC_shieldGroundFrictionMultiplier) \
    X(0x3f0, F32, x3F0) \
    X(0x3f4, OPAQUE32, x3F4) \
    X(0x3f8, OPAQUE32, x3F8) \
    X(0x3fc, I32, x3FC) \
    X(0x400, F32, x400) \
    X(0x404, F32, x404) \
    X(0x408, F32, x408) \
    X(0x40c, F32, x40C) \
    X(0x410, I32, x410) \
    X(0x414, I32, x414) \
    X(0x418, I32, x418) \
    X(0x41c, I32, x41C) \
    X(0x420, F32, x420) \
    X(0x424, F32, x424) \
    X(0x428, I32, x428) \
    X(0x42c, F32, x42C) \
    X(0x430, F32, x430) \
    X(0x434, F32, x434) \
    X(0x438, F32, x438) \
    X(0x43c, F32, x43C) \
    X(0x440, F32, x440) \
    X(0x444, F32, x444) \
    X(0x448, F32, x448) \
    X(0x44c, F32, x44C) \
    X(0x450, F32, x450) \
    X(0x454, F32, x454) \
    X(0x458, F32, x458) \
    X(0x45c, F32, x45C) \
    X(0x460, F32, x460) \
    X(0x464, F32, x464) \
    X(0x468, F32, x468) \
    X(0x46c, F32, x46C) \
    X(0x470, F32, x470) \
    X(0x474, F32, teeter_walk_threshold) \
    X(0x478, F32, x478) \
    X(0x47c, F32, x47C) \
    X(0x480, F32, x480) \
    X(0x484, F32, x484) \
    X(0x488, I32, x488) \
    X(0x48c, F32, x48C) \
    X(0x490, F32, x490) \
    X(0x494, F32, x494) \
    X(0x498, I32, ledge_cooldown) \
    X(0x49c, I32, x49C) \
    X(0x4a0, F32, x4A0) \
    X(0x4a4, F32, x4A4) \
    X(0x4a8, F32, x4A8) \
    X(0x4ac, F32, x4AC) \
    X(0x4b0, F32, sdi_min_stick_mag) \
    X(0x4b4, I32, sdi_stick_window) \
    X(0x4b8, F32, sdi_pos_scale) \
    X(0x4bc, F32, x4BC) \
    X(0x4c0, F32, x4C0) \
    X(0x4c4, I32, x4C4) \
    X(0x4c8, I32, x4C8) \
    X(0x4cc, I32, x4CC) \
    X(0x4d0, F32, x4D0) \
    X(0x4d4, F32, x4D4) \
    X(0x4d8, U32, x4D8) \
    X(0x4dc, F32, x4DC.x) \
    X(0x4e0, F32, x4DC.y) \
    X(0x4e4, F32, x4E4.x) \
    X(0x4e8, F32, x4E4.y) \
    X(0x4ec, F32, x4E4.z) \
    X(0x4f0, F32, x4F0) \
    X(0x4f4, F32, x4F4) \
    X(0x4f8, U32, x4F8) \
    X(0x4fc, U32, x4FC) \
    X(0x500, OPAQUE32, x500) \
    X(0x504, I32, x504) \
    X(0x508, OPAQUE32, x508) \
    X(0x50c, OPAQUE32, x50C) \
    X(0x510, F32, x510) \
    X(0x514, F32, x514) \
    X(0x518, OPAQUE32, x518) \
    X(0x51c, F32, x51C_radians) \
    X(0x520, I32, x520) \
    X(0x524, OPAQUE32, x524) \
    X(0x528, OPAQUE32, x528) \
    X(0x52c, OPAQUE32, x52C) \
    X(0x530, OPAQUE32, x530) \
    X(0x534, OPAQUE32, x534) \
    X(0x538, OPAQUE32, x538) \
    X(0x53c, F32, x53C) \
    X(0x540, F32, x540) \
    X(0x544, OPAQUE32, x544) \
    X(0x548, F32, x548) \
    X(0x54c, F32, x54C) \
    X(0x550, F32, x550) \
    X(0x554, F32, x554) \
    X(0x558, F32, x558) \
    X(0x55c, F32, x55C) \
    X(0x560, F32, x560_radians) \
    X(0x564, F32, x564) \
    X(0x568, F32, x568) \
    X(0x56c, F32, x56C) \
    X(0x570, F32, x570) \
    X(0x574, F32, x574) \
    X(0x578, F32, x578) \
    X(0x57c, I32, x57C) \
    X(0x580, I32, x580) \
    X(0x584, I32, x584) \
    X(0x588, I32, x588) \
    X(0x58c, F32, x58C) \
    X(0x590, F32, x590) \
    X(0x594, F32, open_parasol_threshold) \
    X(0x598, F32, close_parasol_threshold) \
    X(0x59c, F32, x59C) \
    X(0x5a0, F32, x5A0) \
    X(0x5a4, I32, x5A4) \
    X(0x5a8, F32, x5A8) \
    X(0x5ac, F32, x5AC) \
    X(0x5b0, F32, x5B0) \
    X(0x5b4, I32, x5B4) \
    X(0x5b8, F32, x5B8) \
    X(0x5bc, OPAQUE32, x5BC) \
    X(0x5c0, F32, x5C0) \
    X(0x5c4, OPAQUE32, x5C4) \
    X(0x5c8, I32, x5C8) \
    X(0x5cc, F32, x5CC) \
    X(0x5d0, OPAQUE32, x5D0) \
    X(0x5d4, OPAQUE32, x5D4) \
    X(0x5d8, I32, x5D8) \
    X(0x5dc, U32, bury_timer_unk1) \
    X(0x5e0, U32, bury_timer_unk2) \
    X(0x5e4, U32, bury_timer_unk3) \
    X(0x5e8, F32, x5E8) \
    X(0x5ec, OPAQUE32, x5EC) \
    X(0x5f0, U32, x5F0) \
    X(0x5f4, I32, x5F4) \
    X(0x5f8, F32, x5F8) \
    X(0x5fc, F32, x5FC) \
    X(0x600, F32, x600) \
    X(0x604, F32, x604) \
    X(0x608, F32, x608) \
    X(0x60c, F32, x60C) \
    X(0x610, F32, x610) \
    X(0x614, F32, x614) \
    X(0x618, F32, x618) \
    X(0x61c, F32, x61C) \
    X(0x620, I32, x620) \
    X(0x624, F32, x624) \
    X(0x628, F32, x628) \
    X(0x62c, F32, x62C) \
    X(0x630, F32, x630) \
    X(0x634, F32, x634) \
    X(0x638, F32, x638) \
    X(0x63c, F32, x63C) \
    X(0x640, F32, x640) \
    X(0x644, F32, x644) \
    X(0x648, I32, x648) \
    X(0x64c, F32, x64C) \
    X(0x650, F32, x650) \
    X(0x654, F32, x654) \
    X(0x658, F32, x658) \
    X(0x65c, F32, x65C) \
    X(0x660, F32, x660) \
    X(0x664, F32, x664) \
    X(0x668, F32, pressed_inputs) \
    X(0x66c, F32, released_inputs) \
    X(0x670, F32, x670) \
    X(0x674, F32, x674) \
    X(0x678, F32, x678) \
    X(0x67c, F32, x67C) \
    X(0x680, F32, x680) \
    X(0x684, F32, x684) \
    X(0x688, I32, x688) \
    X(0x68c, I32, x68C) \
    X(0x690, I32, x690) \
    X(0x694, F32, x694) \
    X(0x698, F32, x698) \
    X(0x69c, F32, warpstarfall_drift_scaling) \
    X(0x6a0, F32, warpstarfall_drift_flat) \
    X(0x6a4, F32, warpstarfall_drift_max) \
    X(0x6a8, F32, x6A8) \
    X(0x6ac, I32, x6AC) \
    X(0x6b0, I32, x6B0) \
    X(0x6b4, I32, x6B4) \
    X(0x6b8, I32, x6B8) \
    X(0x6bc, I32, x6BC) \
    X(0x6c0, I32, x6C0) \
    X(0x6c4, F32, x6C4) \
    X(0x6c8, I32, x6C8) \
    X(0x6cc, I32, x6CC) \
    X(0x6d0, F32, x6D0) \
    X(0x6d4, I32, x6D4) \
    X(0x6d8, I32, x6D8[0]) \
    X(0x6dc, BYTE, x6DC_colorsByPlayer[0].r) \
    X(0x6dd, BYTE, x6DC_colorsByPlayer[0].g) \
    X(0x6de, BYTE, x6DC_colorsByPlayer[0].b) \
    X(0x6df, BYTE, x6DC_colorsByPlayer[0].a) \
    X(0x6e0, BYTE, x6DC_colorsByPlayer[1].r) \
    X(0x6e1, BYTE, x6DC_colorsByPlayer[1].g) \
    X(0x6e2, BYTE, x6DC_colorsByPlayer[1].b) \
    X(0x6e3, BYTE, x6DC_colorsByPlayer[1].a) \
    X(0x6e4, BYTE, x6DC_colorsByPlayer[2].r) \
    X(0x6e5, BYTE, x6DC_colorsByPlayer[2].g) \
    X(0x6e6, BYTE, x6DC_colorsByPlayer[2].b) \
    X(0x6e7, BYTE, x6DC_colorsByPlayer[2].a) \
    X(0x6e8, BYTE, x6DC_colorsByPlayer[3].r) \
    X(0x6e9, BYTE, x6DC_colorsByPlayer[3].g) \
    X(0x6ea, BYTE, x6DC_colorsByPlayer[3].b) \
    X(0x6eb, BYTE, x6DC_colorsByPlayer[3].a) \
    X(0x6ec, BYTE, x6EC[0]) \
    X(0x6ed, BYTE, x6EC[1]) \
    X(0x6ee, BYTE, x6EC[2]) \
    X(0x6ef, BYTE, x6EC[3]) \
    X(0x6f0, F32, metal_armor) \
    X(0x6f4, I32, x6F4_unkDamage) \
    X(0x6f8, I32, x6F8) \
    X(0x6fc, I32, x6FC) \
    X(0x700, I32, x700) \
    X(0x704, F32, x704) \
    X(0x708, F32, x708) \
    X(0x70c, F32, x70C) \
    X(0x710, F32, x710) \
    X(0x714, F32, x714) \
    X(0x718, F32, kb_ice_mul) \
    X(0x71c, F32, x71C) \
    X(0x720, F32, x720) \
    X(0x724, F32, x724) \
    X(0x728, F32, x728) \
    X(0x72c, F32, x72C) \
    X(0x730, F32, x730) \
    X(0x734, F32, leadead_grab_timer_step) \
    X(0x738, F32, leadead_grab_break_threshold) \
    X(0x73c, I32, x73C) \
    X(0x740, F32, x740) \
    X(0x744, F32, x744) \
    X(0x748, F32, x748) \
    X(0x74c, F32, x74C) \
    X(0x750, F32, x750) \
    X(0x754, F32, x754) \
    X(0x758, F32, x758) \
    X(0x75c, F32, x75C) \
    X(0x760, I32, x760) \
    X(0x764, I32, x764) \
    X(0x768, F32, x768) \
    X(0x76c, F32, x76C) \
    X(0x770, F32, x770) \
    X(0x774, I32, x774) \
    X(0x778, F32, passive_wall_vel_y_base) \
    X(0x77c, F32, damageice_gravity_mult) \
    X(0x780, F32, damageice_min_speed) \
    X(0x784, F32, damageice_speed_mult_on_break) \
    X(0x788, F32, damageice_rot_speed_min) \
    X(0x78c, F32, damageice_rot_speed_max) \
    X(0x790, F32, x790_damageice_unk) \
    X(0x794, F32, x794_damageice_unk) \
    X(0x798, F32, x798_damageice_unk) \
    X(0x79c, F32, damageice_dmg_time_reduction_mult) \
    X(0x7a0, F32, damageice_ice_size) \
    X(0x7a4, F32, damageicejump_escape_time) \
    X(0x7a8, F32, x7A8) \
    X(0x7ac, I32, x7AC) \
    X(0x7b0, I32, x7B0) \
    X(0x7b4, I32, x7B4_unkDamage) \
    X(0x7b8, F32, x7B8) \
    X(0x7bc, F32, x7BC) \
    X(0x7c0, F32, x7C0) \
    X(0x7c4, F32, kb_smashcharge_mul) \
    X(0x7c8, F32, x7C8) \
    X(0x7cc, I32, x7CC) \
    X(0x7d0, I32, x7D0) \
    X(0x7d4, F32, hit_weight_mul) \
    X(0x7d8, BYTE, x7D8.r) \
    X(0x7d9, BYTE, x7D8.g) \
    X(0x7da, BYTE, x7D8.b) \
    X(0x7db, BYTE, x7D8.a) \
    X(0x7dc, I32, x7DC) \
    X(0x7e0, I32, x7E0) \
    X(0x7e4, F32, x7E4_scaleZ) \
    X(0x7e8, U32, unk_kb_angle_min) \
    X(0x7ec, U32, unk_kb_angle_max) \
    X(0x7f0, I32, x7F0) \
    X(0x7f4, F32, x7F4) \
    X(0x7f8, F32, x7F8) \
    X(0x7fc, F32, x7FC) \
    X(0x800, F32, x800) \
    X(0x804, F32, x804) \
    X(0x808, F32, x808.x) \
    X(0x80c, F32, x808.y) \
    X(0x810, F32, x808.z) \
    X(0x814, I32, x814)

#define MELEE_WEB_COMMON_ROOTS(X) \
    X(0, p_ftCommonData) \
    X(1, Fighter_804D6550) \
    X(2, Fighter_804D654C) \
    X(3, Fighter_804D6548) \
    X(4, ftPartsTable) \
    X(5, Fighter_804D6540) \
    X(6, Fighter_804D653C) \
    X(7, Fighter_804D6538) \
    X(8, Fighter_804D6534) \
    X(9, Fighter_804D6530) \
    X(10, Fighter_GrabMashShake) \
    X(11, Fighter_SmashChargeShakeTable) \
    X(12, Fighter_804D6524) \
    X(13, Fighter_804D6520) \
    X(14, Fighter_804D651C) \
    X(15, Fighter_804D6518) \
    X(16, Fighter_804D6514) \
    X(17, Fighter_804D6510) \
    X(18, Fighter_804D650C) \
    X(19, Fighter_804D6508) \
    X(20, Fighter_804D6504) \
    X(21, gCrowdConfig) \
    X(22, Fighter_804D64FC)

#ifdef __cplusplus
#define MELEE_WEB_COMMON_ASSERT static_assert
#else
#define MELEE_WEB_COMMON_ASSERT _Static_assert
#endif
// Invoke for the actual original ftCommonData only in its 32-bit target ABI.
#define MELEE_WEB_COMMON_ASSERT_LAYOUT(T) \
    MELEE_WEB_COMMON_ASSERT(sizeof(T) == MELEE_WEB_COMMON_SCALAR_BYTES, "common scalar size"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, horizontal_stick_deadzone) == 0x000 && sizeof(((T*)0)->horizontal_stick_deadzone) == 4, "common field horizontal_stick_deadzone"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, vertical_stick_deadzone) == 0x004 && sizeof(((T*)0)->vertical_stick_deadzone) == 4, "common field vertical_stick_deadzone"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, horizontal_stick_smash_deadzone) == 0x008 && sizeof(((T*)0)->horizontal_stick_smash_deadzone) == 4, "common field horizontal_stick_smash_deadzone"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, vertical_stick_smash_deadzone) == 0x00c && sizeof(((T*)0)->vertical_stick_smash_deadzone) == 4, "common field vertical_stick_smash_deadzone"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, analog_shoulder_deadzone) == 0x010 && sizeof(((T*)0)->analog_shoulder_deadzone) == 4, "common field analog_shoulder_deadzone"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, z_press_analog_value) == 0x014 && sizeof(((T*)0)->z_press_analog_value) == 4, "common field z_press_analog_value"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, shield_press_threshold) == 0x018 && sizeof(((T*)0)->shield_press_threshold) == 4, "common field shield_press_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1C) == 0x01c && sizeof(((T*)0)->x1C) == 4, "common field x1C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x20_radians) == 0x020 && sizeof(((T*)0)->x20_radians) == 4, "common field x20_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, walk_stick_threshold) == 0x024 && sizeof(((T*)0)->walk_stick_threshold) == 4, "common field walk_stick_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, walk_middle_animation_stick_threshold) == 0x028 && sizeof(((T*)0)->walk_middle_animation_stick_threshold) == 4, "common field walk_middle_animation_stick_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, walk_fast_stick_threshold) == 0x02c && sizeof(((T*)0)->walk_fast_stick_threshold) == 4, "common field walk_fast_stick_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, walk_accel_taper_gain) == 0x030 && sizeof(((T*)0)->walk_accel_taper_gain) == 4, "common field walk_accel_taper_gain"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x34) == 0x034 && sizeof(((T*)0)->x34) == 4, "common field x34"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x38_someLStickXThreshold) == 0x038 && sizeof(((T*)0)->x38_someLStickXThreshold) == 4, "common field x38_someLStickXThreshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, dash_smash_stick_threshold) == 0x03c && sizeof(((T*)0)->dash_smash_stick_threshold) == 4, "common field dash_smash_stick_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, dash_smash_window) == 0x040 && sizeof(((T*)0)->dash_smash_window) == 4, "common field dash_smash_window"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x44) == 0x044 && sizeof(((T*)0)->x44) == 4, "common field x44"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x48) == 0x048 && sizeof(((T*)0)->x48) == 4, "common field x48"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4C) == 0x04c && sizeof(((T*)0)->x4C) == 4, "common field x4C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x50) == 0x050 && sizeof(((T*)0)->x50) == 4, "common field x50"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x54) == 0x054 && sizeof(((T*)0)->x54) == 4, "common field x54"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x58_someLStickXThreshold) == 0x058 && sizeof(((T*)0)->x58_someLStickXThreshold) == 4, "common field x58_someLStickXThreshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, run_accel_taper_gain) == 0x05c && sizeof(((T*)0)->run_accel_taper_gain) == 4, "common field run_accel_taper_gain"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, run_dash_turn_friction_multiplier) == 0x060 && sizeof(((T*)0)->run_dash_turn_friction_multiplier) == 4, "common field run_dash_turn_friction_multiplier"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x64) == 0x064 && sizeof(((T*)0)->x64) == 4, "common field x64"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x68) == 0x068 && sizeof(((T*)0)->x68) == 4, "common field x68"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, friction_when_above_walk_speed) == 0x06c && sizeof(((T*)0)->friction_when_above_walk_speed) == 4, "common field friction_when_above_walk_speed"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, tap_jump_threshold) == 0x070 && sizeof(((T*)0)->tap_jump_threshold) == 4, "common field tap_jump_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, tap_jump_window) == 0x074 && sizeof(((T*)0)->tap_jump_window) == 4, "common field tap_jump_window"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x78) == 0x078 && sizeof(((T*)0)->x78) == 4, "common field x78"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, tap_jump_release_threshold) == 0x07c && sizeof(((T*)0)->tap_jump_release_threshold) == 4, "common field tap_jump_release_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, relaxed_tap_jump_threshold) == 0x080 && sizeof(((T*)0)->relaxed_tap_jump_threshold) == 4, "common field relaxed_tap_jump_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x84) == 0x084 && sizeof(((T*)0)->x84) == 4, "common field x84"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x88) == 0x088 && sizeof(((T*)0)->x88) == 4, "common field x88"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x8C) == 0x08c && sizeof(((T*)0)->x8C) == 4, "common field x8C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x90) == 0x090 && sizeof(((T*)0)->x90) == 4, "common field x90"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x94) == 0x094 && sizeof(((T*)0)->x94) == 4, "common field x94"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x98) == 0x098 && sizeof(((T*)0)->x98) == 4, "common field x98"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x9C_radians) == 0x09c && sizeof(((T*)0)->x9C_radians) == 4, "common field x9C_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xA0_radians) == 0x0a0 && sizeof(((T*)0)->xA0_radians) == 4, "common field xA0_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xA4_radians) == 0x0a4 && sizeof(((T*)0)->xA4_radians) == 4, "common field xA4_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xA8_radians) == 0x0a8 && sizeof(((T*)0)->xA8_radians) == 4, "common field xA8_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, attackhi3_stick_threshold_y) == 0x0ac && sizeof(((T*)0)->attackhi3_stick_threshold_y) == 4, "common field attackhi3_stick_threshold_y"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xB0) == 0x0b0 && sizeof(((T*)0)->xB0) == 4, "common field xB0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xB4) == 0x0b4 && sizeof(((T*)0)->xB4) == 4, "common field xB4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xB8_radians) == 0x0b8 && sizeof(((T*)0)->xB8_radians) == 4, "common field xB8_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xBC_radians) == 0x0bc && sizeof(((T*)0)->xBC_radians) == 4, "common field xBC_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xC0_radians) == 0x0c0 && sizeof(((T*)0)->xC0_radians) == 4, "common field xC0_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xC4_radians) == 0x0c4 && sizeof(((T*)0)->xC4_radians) == 4, "common field xC4_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xC8) == 0x0c8 && sizeof(((T*)0)->xC8) == 4, "common field xC8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xCC) == 0x0cc && sizeof(((T*)0)->xCC) == 4, "common field xCC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xD0) == 0x0d0 && sizeof(((T*)0)->xD0) == 4, "common field xD0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xD4) == 0x0d4 && sizeof(((T*)0)->xD4) == 4, "common field xD4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xD8) == 0x0d8 && sizeof(((T*)0)->xD8) == 4, "common field xD8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xDC) == 0x0dc && sizeof(((T*)0)->xDC) == 4, "common field xDC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xE0) == 0x0e0 && sizeof(((T*)0)->xE0) == 4, "common field xE0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xE4) == 0x0e4 && sizeof(((T*)0)->xE4) == 4, "common field xE4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xE8) == 0x0e8 && sizeof(((T*)0)->xE8) == 4, "common field xE8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xEC) == 0x0ec && sizeof(((T*)0)->xEC) == 4, "common field xEC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xF0) == 0x0f0 && sizeof(((T*)0)->xF0) == 4, "common field xF0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xF4) == 0x0f4 && sizeof(((T*)0)->xF4) == 4, "common field xF4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xF8) == 0x0f8 && sizeof(((T*)0)->xF8) == 4, "common field xF8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, xFC) == 0x0fc && sizeof(((T*)0)->xFC) == 4, "common field xFC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x100) == 0x100 && sizeof(((T*)0)->x100) == 4, "common field x100"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, kb_min) == 0x104 && sizeof(((T*)0)->kb_min) == 4, "common field kb_min"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x108) == 0x108 && sizeof(((T*)0)->x108) == 4, "common field x108"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x10C) == 0x10c && sizeof(((T*)0)->x10C) == 4, "common field x10C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x110) == 0x110 && sizeof(((T*)0)->x110) == 4, "common field x110"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x114) == 0x114 && sizeof(((T*)0)->x114) == 4, "common field x114"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x118) == 0x118 && sizeof(((T*)0)->x118) == 4, "common field x118"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x11C) == 0x11c && sizeof(((T*)0)->x11C) == 4, "common field x11C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x120) == 0x120 && sizeof(((T*)0)->x120) == 4, "common field x120"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, kb_squat_mul) == 0x124 && sizeof(((T*)0)->kb_squat_mul) == 4, "common field kb_squat_mul"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x128) == 0x128 && sizeof(((T*)0)->x128) == 4, "common field x128"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x12C) == 0x12c && sizeof(((T*)0)->x12C) == 4, "common field x12C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x130) == 0x130 && sizeof(((T*)0)->x130) == 4, "common field x130"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x134) == 0x134 && sizeof(((T*)0)->x134) == 4, "common field x134"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x138) == 0x138 && sizeof(((T*)0)->x138) == 4, "common field x138"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x13C) == 0x13c && sizeof(((T*)0)->x13C) == 4, "common field x13C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x140) == 0x140 && sizeof(((T*)0)->x140) == 4, "common field x140"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x144_radians) == 0x144 && sizeof(((T*)0)->x144_radians) == 4, "common field x144_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x148) == 0x148 && sizeof(((T*)0)->x148) == 4, "common field x148"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x14C) == 0x14c && sizeof(((T*)0)->x14C) == 4, "common field x14C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x150) == 0x150 && sizeof(((T*)0)->x150) == 4, "common field x150"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x154) == 0x154 && sizeof(((T*)0)->x154) == 4, "common field x154"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x158) == 0x158 && sizeof(((T*)0)->x158) == 4, "common field x158"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x15C) == 0x15c && sizeof(((T*)0)->x15C) == 4, "common field x15C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x160) == 0x160 && sizeof(((T*)0)->x160) == 4, "common field x160"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x164) == 0x164 && sizeof(((T*)0)->x164) == 4, "common field x164"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x168) == 0x168 && sizeof(((T*)0)->x168) == 4, "common field x168"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x16C) == 0x16c && sizeof(((T*)0)->x16C) == 4, "common field x16C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x170) == 0x170 && sizeof(((T*)0)->x170) == 4, "common field x170"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x174) == 0x174 && sizeof(((T*)0)->x174) == 4, "common field x174"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x178) == 0x178 && sizeof(((T*)0)->x178) == 4, "common field x178"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x17C) == 0x17c && sizeof(((T*)0)->x17C) == 4, "common field x17C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x180) == 0x180 && sizeof(((T*)0)->x180) == 4, "common field x180"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x184) == 0x184 && sizeof(((T*)0)->x184) == 4, "common field x184"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x188) == 0x188 && sizeof(((T*)0)->x188) == 4, "common field x188"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x18C) == 0x18c && sizeof(((T*)0)->x18C) == 4, "common field x18C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x190) == 0x190 && sizeof(((T*)0)->x190) == 4, "common field x190"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x194_unkHitLagFrames) == 0x194 && sizeof(((T*)0)->x194_unkHitLagFrames) == 4, "common field x194_unkHitLagFrames"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x198) == 0x198 && sizeof(((T*)0)->x198) == 4, "common field x198"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x19C) == 0x19c && sizeof(((T*)0)->x19C) == 4, "common field x19C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1A0) == 0x1a0 && sizeof(((T*)0)->x1A0) == 4, "common field x1A0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1A4) == 0x1a4 && sizeof(((T*)0)->x1A4) == 4, "common field x1A4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1A8) == 0x1a8 && sizeof(((T*)0)->x1A8) == 4, "common field x1A8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1AC) == 0x1ac && sizeof(((T*)0)->x1AC) == 4, "common field x1AC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1B0) == 0x1b0 && sizeof(((T*)0)->x1B0) == 4, "common field x1B0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1B4) == 0x1b4 && sizeof(((T*)0)->x1B4) == 4, "common field x1B4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1B8) == 0x1b8 && sizeof(((T*)0)->x1B8) == 4, "common field x1B8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1BC) == 0x1bc && sizeof(((T*)0)->x1BC) == 4, "common field x1BC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1C0) == 0x1c0 && sizeof(((T*)0)->x1C0) == 4, "common field x1C0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1C4) == 0x1c4 && sizeof(((T*)0)->x1C4) == 4, "common field x1C4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1C8) == 0x1c8 && sizeof(((T*)0)->x1C8) == 4, "common field x1C8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1CC) == 0x1cc && sizeof(((T*)0)->x1CC) == 4, "common field x1CC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1D0) == 0x1d0 && sizeof(((T*)0)->x1D0) == 4, "common field x1D0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1D4) == 0x1d4 && sizeof(((T*)0)->x1D4) == 4, "common field x1D4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1D8) == 0x1d8 && sizeof(((T*)0)->x1D8) == 4, "common field x1D8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1DC) == 0x1dc && sizeof(((T*)0)->x1DC) == 4, "common field x1DC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1E0) == 0x1e0 && sizeof(((T*)0)->x1E0) == 4, "common field x1E0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1E4) == 0x1e4 && sizeof(((T*)0)->x1E4) == 4, "common field x1E4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1E8_radians) == 0x1e8 && sizeof(((T*)0)->x1E8_radians) == 4, "common field x1E8_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1EC) == 0x1ec && sizeof(((T*)0)->x1EC) == 4, "common field x1EC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1F0) == 0x1f0 && sizeof(((T*)0)->x1F0) == 4, "common field x1F0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1F4) == 0x1f4 && sizeof(((T*)0)->x1F4) == 4, "common field x1F4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1F8) == 0x1f8 && sizeof(((T*)0)->x1F8) == 4, "common field x1F8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x1FC) == 0x1fc && sizeof(((T*)0)->x1FC) == 4, "common field x1FC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x200) == 0x200 && sizeof(((T*)0)->x200) == 4, "common field x200"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x204_knockbackFrameDecay) == 0x204 && sizeof(((T*)0)->x204_knockbackFrameDecay) == 4, "common field x204_knockbackFrameDecay"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x208) == 0x208 && sizeof(((T*)0)->x208) == 4, "common field x208"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x20C) == 0x20c && sizeof(((T*)0)->x20C) == 4, "common field x20C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x210) == 0x210 && sizeof(((T*)0)->x210) == 4, "common field x210"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x214) == 0x214 && sizeof(((T*)0)->x214) == 4, "common field x214"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x218) == 0x218 && sizeof(((T*)0)->x218) == 4, "common field x218"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x21C) == 0x21c && sizeof(((T*)0)->x21C) == 4, "common field x21C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x220) == 0x220 && sizeof(((T*)0)->x220) == 4, "common field x220"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x224) == 0x224 && sizeof(((T*)0)->x224) == 4, "common field x224"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x228) == 0x228 && sizeof(((T*)0)->x228) == 4, "common field x228"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x22C) == 0x22c && sizeof(((T*)0)->x22C) == 4, "common field x22C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x230) == 0x230 && sizeof(((T*)0)->x230) == 4, "common field x230"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x234_radians) == 0x234 && sizeof(((T*)0)->x234_radians) == 4, "common field x234_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x238_radians) == 0x238 && sizeof(((T*)0)->x238_radians) == 4, "common field x238_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x23C) == 0x23c && sizeof(((T*)0)->x23C) == 4, "common field x23C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x240) == 0x240 && sizeof(((T*)0)->x240) == 4, "common field x240"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x244) == 0x244 && sizeof(((T*)0)->x244) == 4, "common field x244"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x248) == 0x248 && sizeof(((T*)0)->x248) == 4, "common field x248"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x24C) == 0x24c && sizeof(((T*)0)->x24C) == 4, "common field x24C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x250) == 0x250 && sizeof(((T*)0)->x250) == 4, "common field x250"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x254) == 0x254 && sizeof(((T*)0)->x254) == 4, "common field x254"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x258) == 0x258 && sizeof(((T*)0)->x258) == 4, "common field x258"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x25C) == 0x25c && sizeof(((T*)0)->x25C) == 4, "common field x25C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x260_startShieldHealth) == 0x260 && sizeof(((T*)0)->x260_startShieldHealth) == 4, "common field x260_startShieldHealth"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x264) == 0x264 && sizeof(((T*)0)->x264) == 4, "common field x264"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x268) == 0x268 && sizeof(((T*)0)->x268) == 4, "common field x268"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x26C) == 0x26c && sizeof(((T*)0)->x26C) == 4, "common field x26C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x270) == 0x270 && sizeof(((T*)0)->x270) == 4, "common field x270"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x274) == 0x274 && sizeof(((T*)0)->x274) == 4, "common field x274"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x278) == 0x278 && sizeof(((T*)0)->x278) == 4, "common field x278"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x27C) == 0x27c && sizeof(((T*)0)->x27C) == 4, "common field x27C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x280_unkShieldHealth) == 0x280 && sizeof(((T*)0)->x280_unkShieldHealth) == 4, "common field x280_unkShieldHealth"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x284) == 0x284 && sizeof(((T*)0)->x284) == 4, "common field x284"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x288) == 0x288 && sizeof(((T*)0)->x288) == 4, "common field x288"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x28C) == 0x28c && sizeof(((T*)0)->x28C) == 4, "common field x28C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x290) == 0x290 && sizeof(((T*)0)->x290) == 4, "common field x290"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x294) == 0x294 && sizeof(((T*)0)->x294) == 4, "common field x294"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x298) == 0x298 && sizeof(((T*)0)->x298) == 4, "common field x298"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x29C) == 0x29c && sizeof(((T*)0)->x29C) == 4, "common field x29C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, powershield_input_window) == 0x2a0 && sizeof(((T*)0)->powershield_input_window) == 4, "common field powershield_input_window"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2A4) == 0x2a4 && sizeof(((T*)0)->x2A4) == 4, "common field x2A4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2A8) == 0x2a8 && sizeof(((T*)0)->x2A8) == 4, "common field x2A8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2AC) == 0x2ac && sizeof(((T*)0)->x2AC) == 4, "common field x2AC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2B0) == 0x2b0 && sizeof(((T*)0)->x2B0) == 4, "common field x2B0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2B4) == 0x2b4 && sizeof(((T*)0)->x2B4) == 4, "common field x2B4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2B8) == 0x2b8 && sizeof(((T*)0)->x2B8) == 4, "common field x2B8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2BC) == 0x2bc && sizeof(((T*)0)->x2BC) == 4, "common field x2BC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2C0) == 0x2c0 && sizeof(((T*)0)->x2C0) == 4, "common field x2C0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2C4) == 0x2c4 && sizeof(((T*)0)->x2C4) == 4, "common field x2C4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2C8) == 0x2c8 && sizeof(((T*)0)->x2C8) == 4, "common field x2C8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2CC) == 0x2cc && sizeof(((T*)0)->x2CC) == 4, "common field x2CC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2D0) == 0x2d0 && sizeof(((T*)0)->x2D0) == 4, "common field x2D0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2D4) == 0x2d4 && sizeof(((T*)0)->x2D4) == 4, "common field x2D4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2D8) == 0x2d8 && sizeof(((T*)0)->x2D8) == 4, "common field x2D8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2DC) == 0x2dc && sizeof(((T*)0)->x2DC) == 4, "common field x2DC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2E0) == 0x2e0 && sizeof(((T*)0)->x2E0) == 4, "common field x2E0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2E4) == 0x2e4 && sizeof(((T*)0)->x2E4) == 4, "common field x2E4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2E8) == 0x2e8 && sizeof(((T*)0)->x2E8) == 4, "common field x2E8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2EC) == 0x2ec && sizeof(((T*)0)->x2EC) == 4, "common field x2EC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2F0) == 0x2f0 && sizeof(((T*)0)->x2F0) == 4, "common field x2F0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2F4) == 0x2f4 && sizeof(((T*)0)->x2F4) == 4, "common field x2F4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2F8) == 0x2f8 && sizeof(((T*)0)->x2F8) == 4, "common field x2F8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x2FC) == 0x2fc && sizeof(((T*)0)->x2FC) == 4, "common field x2FC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x300) == 0x300 && sizeof(((T*)0)->x300) == 4, "common field x300"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x304) == 0x304 && sizeof(((T*)0)->x304) == 4, "common field x304"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x308) == 0x308 && sizeof(((T*)0)->x308) == 4, "common field x308"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x30C) == 0x30c && sizeof(((T*)0)->x30C) == 4, "common field x30C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x310) == 0x310 && sizeof(((T*)0)->x310) == 4, "common field x310"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x314) == 0x314 && sizeof(((T*)0)->x314) == 4, "common field x314"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x318) == 0x318 && sizeof(((T*)0)->x318) == 4, "common field x318"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x31C) == 0x31c && sizeof(((T*)0)->x31C) == 4, "common field x31C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x320) == 0x320 && sizeof(((T*)0)->x320) == 4, "common field x320"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x324) == 0x324 && sizeof(((T*)0)->x324) == 4, "common field x324"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x328) == 0x328 && sizeof(((T*)0)->x328) == 4, "common field x328"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, escapeair_deadzone.x) == 0x32c && sizeof(((T*)0)->escapeair_deadzone.x) == 4, "common field escapeair_deadzone.x"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, escapeair_deadzone.y) == 0x330 && sizeof(((T*)0)->escapeair_deadzone.y) == 4, "common field escapeair_deadzone.y"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x334) == 0x334 && sizeof(((T*)0)->x334) == 4, "common field x334"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, escapeair_force) == 0x338 && sizeof(((T*)0)->escapeair_force) == 4, "common field escapeair_force"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, escapeair_decay) == 0x33c && sizeof(((T*)0)->escapeair_decay) == 4, "common field escapeair_decay"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x340) == 0x340 && sizeof(((T*)0)->x340) == 4, "common field x340"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x344) == 0x344 && sizeof(((T*)0)->x344) == 4, "common field x344"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x348) == 0x348 && sizeof(((T*)0)->x348) == 4, "common field x348"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x34C) == 0x34c && sizeof(((T*)0)->x34C) == 4, "common field x34C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x350) == 0x350 && sizeof(((T*)0)->x350) == 4, "common field x350"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x354) == 0x354 && sizeof(((T*)0)->x354) == 4, "common field x354"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x358) == 0x358 && sizeof(((T*)0)->x358) == 4, "common field x358"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x35C) == 0x35c && sizeof(((T*)0)->x35C) == 4, "common field x35C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x360) == 0x360 && sizeof(((T*)0)->x360) == 4, "common field x360"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x364) == 0x364 && sizeof(((T*)0)->x364) == 4, "common field x364"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x368) == 0x368 && sizeof(((T*)0)->x368) == 4, "common field x368"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x36C) == 0x36c && sizeof(((T*)0)->x36C) == 4, "common field x36C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x370) == 0x370 && sizeof(((T*)0)->x370) == 4, "common field x370"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x374) == 0x374 && sizeof(((T*)0)->x374) == 4, "common field x374"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x378) == 0x378 && sizeof(((T*)0)->x378) == 4, "common field x378"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x37C) == 0x37c && sizeof(((T*)0)->x37C) == 4, "common field x37C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x380.state) == 0x380 && sizeof(((T*)0)->x380.state) == 4, "common field x380.state"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x380.damage) == 0x384 && sizeof(((T*)0)->x380.damage) == 4, "common field x380.damage"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x380.kb_angle) == 0x388 && sizeof(((T*)0)->x380.kb_angle) == 4, "common field x380.kb_angle"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x380.unkC) == 0x38c && sizeof(((T*)0)->x380.unkC) == 4, "common field x380.unkC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x380.unk10) == 0x390 && sizeof(((T*)0)->x380.unk10) == 4, "common field x380.unk10"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x380.unk14) == 0x394 && sizeof(((T*)0)->x380.unk14) == 4, "common field x380.unk14"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x380.element) == 0x398 && sizeof(((T*)0)->x380.element) == 4, "common field x380.element"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x380.sfx_severity) == 0x39c && sizeof(((T*)0)->x380.sfx_severity) == 4, "common field x380.sfx_severity"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x380.sfx_kind) == 0x3a0 && sizeof(((T*)0)->x380.sfx_kind) == 4, "common field x380.sfx_kind"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, grab_timer_decrement) == 0x3a4 && sizeof(((T*)0)->grab_timer_decrement) == 4, "common field grab_timer_decrement"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3A8) == 0x3a8 && sizeof(((T*)0)->x3A8) == 4, "common field x3A8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3AC) == 0x3ac && sizeof(((T*)0)->x3AC) == 4, "common field x3AC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3B0) == 0x3b0 && sizeof(((T*)0)->x3B0) == 4, "common field x3B0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, shouldered_anim_rate) == 0x3b4 && sizeof(((T*)0)->shouldered_anim_rate) == 4, "common field shouldered_anim_rate"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3B8) == 0x3b8 && sizeof(((T*)0)->x3B8) == 4, "common field x3B8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3BC) == 0x3bc && sizeof(((T*)0)->x3BC) == 4, "common field x3BC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3C0) == 0x3c0 && sizeof(((T*)0)->x3C0) == 4, "common field x3C0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3C4) == 0x3c4 && sizeof(((T*)0)->x3C4) == 4, "common field x3C4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3C8) == 0x3c8 && sizeof(((T*)0)->x3C8) == 4, "common field x3C8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3CC) == 0x3cc && sizeof(((T*)0)->x3CC) == 4, "common field x3CC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3D0) == 0x3d0 && sizeof(((T*)0)->x3D0) == 4, "common field x3D0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3D4) == 0x3d4 && sizeof(((T*)0)->x3D4) == 4, "common field x3D4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3D8) == 0x3d8 && sizeof(((T*)0)->x3D8) == 4, "common field x3D8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3DC) == 0x3dc && sizeof(((T*)0)->x3DC) == 4, "common field x3DC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3E0) == 0x3e0 && sizeof(((T*)0)->x3E0) == 4, "common field x3E0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3E4) == 0x3e4 && sizeof(((T*)0)->x3E4) == 4, "common field x3E4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3E8_shieldKnockbackFrameDecay) == 0x3e8 && sizeof(((T*)0)->x3E8_shieldKnockbackFrameDecay) == 4, "common field x3E8_shieldKnockbackFrameDecay"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3EC_shieldGroundFrictionMultiplier) == 0x3ec && sizeof(((T*)0)->x3EC_shieldGroundFrictionMultiplier) == 4, "common field x3EC_shieldGroundFrictionMultiplier"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3F0) == 0x3f0 && sizeof(((T*)0)->x3F0) == 4, "common field x3F0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3F4) == 0x3f4 && sizeof(((T*)0)->x3F4) == 4, "common field x3F4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3F8) == 0x3f8 && sizeof(((T*)0)->x3F8) == 4, "common field x3F8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x3FC) == 0x3fc && sizeof(((T*)0)->x3FC) == 4, "common field x3FC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x400) == 0x400 && sizeof(((T*)0)->x400) == 4, "common field x400"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x404) == 0x404 && sizeof(((T*)0)->x404) == 4, "common field x404"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x408) == 0x408 && sizeof(((T*)0)->x408) == 4, "common field x408"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x40C) == 0x40c && sizeof(((T*)0)->x40C) == 4, "common field x40C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x410) == 0x410 && sizeof(((T*)0)->x410) == 4, "common field x410"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x414) == 0x414 && sizeof(((T*)0)->x414) == 4, "common field x414"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x418) == 0x418 && sizeof(((T*)0)->x418) == 4, "common field x418"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x41C) == 0x41c && sizeof(((T*)0)->x41C) == 4, "common field x41C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x420) == 0x420 && sizeof(((T*)0)->x420) == 4, "common field x420"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x424) == 0x424 && sizeof(((T*)0)->x424) == 4, "common field x424"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x428) == 0x428 && sizeof(((T*)0)->x428) == 4, "common field x428"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x42C) == 0x42c && sizeof(((T*)0)->x42C) == 4, "common field x42C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x430) == 0x430 && sizeof(((T*)0)->x430) == 4, "common field x430"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x434) == 0x434 && sizeof(((T*)0)->x434) == 4, "common field x434"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x438) == 0x438 && sizeof(((T*)0)->x438) == 4, "common field x438"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x43C) == 0x43c && sizeof(((T*)0)->x43C) == 4, "common field x43C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x440) == 0x440 && sizeof(((T*)0)->x440) == 4, "common field x440"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x444) == 0x444 && sizeof(((T*)0)->x444) == 4, "common field x444"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x448) == 0x448 && sizeof(((T*)0)->x448) == 4, "common field x448"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x44C) == 0x44c && sizeof(((T*)0)->x44C) == 4, "common field x44C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x450) == 0x450 && sizeof(((T*)0)->x450) == 4, "common field x450"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x454) == 0x454 && sizeof(((T*)0)->x454) == 4, "common field x454"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x458) == 0x458 && sizeof(((T*)0)->x458) == 4, "common field x458"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x45C) == 0x45c && sizeof(((T*)0)->x45C) == 4, "common field x45C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x460) == 0x460 && sizeof(((T*)0)->x460) == 4, "common field x460"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x464) == 0x464 && sizeof(((T*)0)->x464) == 4, "common field x464"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x468) == 0x468 && sizeof(((T*)0)->x468) == 4, "common field x468"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x46C) == 0x46c && sizeof(((T*)0)->x46C) == 4, "common field x46C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x470) == 0x470 && sizeof(((T*)0)->x470) == 4, "common field x470"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, teeter_walk_threshold) == 0x474 && sizeof(((T*)0)->teeter_walk_threshold) == 4, "common field teeter_walk_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x478) == 0x478 && sizeof(((T*)0)->x478) == 4, "common field x478"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x47C) == 0x47c && sizeof(((T*)0)->x47C) == 4, "common field x47C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x480) == 0x480 && sizeof(((T*)0)->x480) == 4, "common field x480"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x484) == 0x484 && sizeof(((T*)0)->x484) == 4, "common field x484"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x488) == 0x488 && sizeof(((T*)0)->x488) == 4, "common field x488"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x48C) == 0x48c && sizeof(((T*)0)->x48C) == 4, "common field x48C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x490) == 0x490 && sizeof(((T*)0)->x490) == 4, "common field x490"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x494) == 0x494 && sizeof(((T*)0)->x494) == 4, "common field x494"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, ledge_cooldown) == 0x498 && sizeof(((T*)0)->ledge_cooldown) == 4, "common field ledge_cooldown"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x49C) == 0x49c && sizeof(((T*)0)->x49C) == 4, "common field x49C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4A0) == 0x4a0 && sizeof(((T*)0)->x4A0) == 4, "common field x4A0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4A4) == 0x4a4 && sizeof(((T*)0)->x4A4) == 4, "common field x4A4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4A8) == 0x4a8 && sizeof(((T*)0)->x4A8) == 4, "common field x4A8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4AC) == 0x4ac && sizeof(((T*)0)->x4AC) == 4, "common field x4AC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, sdi_min_stick_mag) == 0x4b0 && sizeof(((T*)0)->sdi_min_stick_mag) == 4, "common field sdi_min_stick_mag"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, sdi_stick_window) == 0x4b4 && sizeof(((T*)0)->sdi_stick_window) == 4, "common field sdi_stick_window"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, sdi_pos_scale) == 0x4b8 && sizeof(((T*)0)->sdi_pos_scale) == 4, "common field sdi_pos_scale"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4BC) == 0x4bc && sizeof(((T*)0)->x4BC) == 4, "common field x4BC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4C0) == 0x4c0 && sizeof(((T*)0)->x4C0) == 4, "common field x4C0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4C4) == 0x4c4 && sizeof(((T*)0)->x4C4) == 4, "common field x4C4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4C8) == 0x4c8 && sizeof(((T*)0)->x4C8) == 4, "common field x4C8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4CC) == 0x4cc && sizeof(((T*)0)->x4CC) == 4, "common field x4CC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4D0) == 0x4d0 && sizeof(((T*)0)->x4D0) == 4, "common field x4D0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4D4) == 0x4d4 && sizeof(((T*)0)->x4D4) == 4, "common field x4D4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4D8) == 0x4d8 && sizeof(((T*)0)->x4D8) == 4, "common field x4D8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4DC.x) == 0x4dc && sizeof(((T*)0)->x4DC.x) == 4, "common field x4DC.x"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4DC.y) == 0x4e0 && sizeof(((T*)0)->x4DC.y) == 4, "common field x4DC.y"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4E4.x) == 0x4e4 && sizeof(((T*)0)->x4E4.x) == 4, "common field x4E4.x"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4E4.y) == 0x4e8 && sizeof(((T*)0)->x4E4.y) == 4, "common field x4E4.y"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4E4.z) == 0x4ec && sizeof(((T*)0)->x4E4.z) == 4, "common field x4E4.z"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4F0) == 0x4f0 && sizeof(((T*)0)->x4F0) == 4, "common field x4F0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4F4) == 0x4f4 && sizeof(((T*)0)->x4F4) == 4, "common field x4F4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4F8) == 0x4f8 && sizeof(((T*)0)->x4F8) == 4, "common field x4F8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x4FC) == 0x4fc && sizeof(((T*)0)->x4FC) == 4, "common field x4FC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x500) == 0x500 && sizeof(((T*)0)->x500) == 4, "common field x500"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x504) == 0x504 && sizeof(((T*)0)->x504) == 4, "common field x504"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x508) == 0x508 && sizeof(((T*)0)->x508) == 4, "common field x508"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x50C) == 0x50c && sizeof(((T*)0)->x50C) == 4, "common field x50C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x510) == 0x510 && sizeof(((T*)0)->x510) == 4, "common field x510"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x514) == 0x514 && sizeof(((T*)0)->x514) == 4, "common field x514"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x518) == 0x518 && sizeof(((T*)0)->x518) == 4, "common field x518"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x51C_radians) == 0x51c && sizeof(((T*)0)->x51C_radians) == 4, "common field x51C_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x520) == 0x520 && sizeof(((T*)0)->x520) == 4, "common field x520"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x524) == 0x524 && sizeof(((T*)0)->x524) == 4, "common field x524"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x528) == 0x528 && sizeof(((T*)0)->x528) == 4, "common field x528"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x52C) == 0x52c && sizeof(((T*)0)->x52C) == 4, "common field x52C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x530) == 0x530 && sizeof(((T*)0)->x530) == 4, "common field x530"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x534) == 0x534 && sizeof(((T*)0)->x534) == 4, "common field x534"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x538) == 0x538 && sizeof(((T*)0)->x538) == 4, "common field x538"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x53C) == 0x53c && sizeof(((T*)0)->x53C) == 4, "common field x53C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x540) == 0x540 && sizeof(((T*)0)->x540) == 4, "common field x540"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x544) == 0x544 && sizeof(((T*)0)->x544) == 4, "common field x544"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x548) == 0x548 && sizeof(((T*)0)->x548) == 4, "common field x548"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x54C) == 0x54c && sizeof(((T*)0)->x54C) == 4, "common field x54C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x550) == 0x550 && sizeof(((T*)0)->x550) == 4, "common field x550"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x554) == 0x554 && sizeof(((T*)0)->x554) == 4, "common field x554"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x558) == 0x558 && sizeof(((T*)0)->x558) == 4, "common field x558"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x55C) == 0x55c && sizeof(((T*)0)->x55C) == 4, "common field x55C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x560_radians) == 0x560 && sizeof(((T*)0)->x560_radians) == 4, "common field x560_radians"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x564) == 0x564 && sizeof(((T*)0)->x564) == 4, "common field x564"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x568) == 0x568 && sizeof(((T*)0)->x568) == 4, "common field x568"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x56C) == 0x56c && sizeof(((T*)0)->x56C) == 4, "common field x56C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x570) == 0x570 && sizeof(((T*)0)->x570) == 4, "common field x570"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x574) == 0x574 && sizeof(((T*)0)->x574) == 4, "common field x574"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x578) == 0x578 && sizeof(((T*)0)->x578) == 4, "common field x578"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x57C) == 0x57c && sizeof(((T*)0)->x57C) == 4, "common field x57C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x580) == 0x580 && sizeof(((T*)0)->x580) == 4, "common field x580"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x584) == 0x584 && sizeof(((T*)0)->x584) == 4, "common field x584"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x588) == 0x588 && sizeof(((T*)0)->x588) == 4, "common field x588"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x58C) == 0x58c && sizeof(((T*)0)->x58C) == 4, "common field x58C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x590) == 0x590 && sizeof(((T*)0)->x590) == 4, "common field x590"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, open_parasol_threshold) == 0x594 && sizeof(((T*)0)->open_parasol_threshold) == 4, "common field open_parasol_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, close_parasol_threshold) == 0x598 && sizeof(((T*)0)->close_parasol_threshold) == 4, "common field close_parasol_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x59C) == 0x59c && sizeof(((T*)0)->x59C) == 4, "common field x59C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5A0) == 0x5a0 && sizeof(((T*)0)->x5A0) == 4, "common field x5A0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5A4) == 0x5a4 && sizeof(((T*)0)->x5A4) == 4, "common field x5A4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5A8) == 0x5a8 && sizeof(((T*)0)->x5A8) == 4, "common field x5A8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5AC) == 0x5ac && sizeof(((T*)0)->x5AC) == 4, "common field x5AC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5B0) == 0x5b0 && sizeof(((T*)0)->x5B0) == 4, "common field x5B0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5B4) == 0x5b4 && sizeof(((T*)0)->x5B4) == 4, "common field x5B4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5B8) == 0x5b8 && sizeof(((T*)0)->x5B8) == 4, "common field x5B8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5BC) == 0x5bc && sizeof(((T*)0)->x5BC) == 4, "common field x5BC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5C0) == 0x5c0 && sizeof(((T*)0)->x5C0) == 4, "common field x5C0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5C4) == 0x5c4 && sizeof(((T*)0)->x5C4) == 4, "common field x5C4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5C8) == 0x5c8 && sizeof(((T*)0)->x5C8) == 4, "common field x5C8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5CC) == 0x5cc && sizeof(((T*)0)->x5CC) == 4, "common field x5CC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5D0) == 0x5d0 && sizeof(((T*)0)->x5D0) == 4, "common field x5D0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5D4) == 0x5d4 && sizeof(((T*)0)->x5D4) == 4, "common field x5D4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5D8) == 0x5d8 && sizeof(((T*)0)->x5D8) == 4, "common field x5D8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, bury_timer_unk1) == 0x5dc && sizeof(((T*)0)->bury_timer_unk1) == 4, "common field bury_timer_unk1"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, bury_timer_unk2) == 0x5e0 && sizeof(((T*)0)->bury_timer_unk2) == 4, "common field bury_timer_unk2"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, bury_timer_unk3) == 0x5e4 && sizeof(((T*)0)->bury_timer_unk3) == 4, "common field bury_timer_unk3"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5E8) == 0x5e8 && sizeof(((T*)0)->x5E8) == 4, "common field x5E8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5EC) == 0x5ec && sizeof(((T*)0)->x5EC) == 4, "common field x5EC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5F0) == 0x5f0 && sizeof(((T*)0)->x5F0) == 4, "common field x5F0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5F4) == 0x5f4 && sizeof(((T*)0)->x5F4) == 4, "common field x5F4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5F8) == 0x5f8 && sizeof(((T*)0)->x5F8) == 4, "common field x5F8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x5FC) == 0x5fc && sizeof(((T*)0)->x5FC) == 4, "common field x5FC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x600) == 0x600 && sizeof(((T*)0)->x600) == 4, "common field x600"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x604) == 0x604 && sizeof(((T*)0)->x604) == 4, "common field x604"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x608) == 0x608 && sizeof(((T*)0)->x608) == 4, "common field x608"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x60C) == 0x60c && sizeof(((T*)0)->x60C) == 4, "common field x60C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x610) == 0x610 && sizeof(((T*)0)->x610) == 4, "common field x610"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x614) == 0x614 && sizeof(((T*)0)->x614) == 4, "common field x614"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x618) == 0x618 && sizeof(((T*)0)->x618) == 4, "common field x618"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x61C) == 0x61c && sizeof(((T*)0)->x61C) == 4, "common field x61C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x620) == 0x620 && sizeof(((T*)0)->x620) == 4, "common field x620"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x624) == 0x624 && sizeof(((T*)0)->x624) == 4, "common field x624"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x628) == 0x628 && sizeof(((T*)0)->x628) == 4, "common field x628"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x62C) == 0x62c && sizeof(((T*)0)->x62C) == 4, "common field x62C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x630) == 0x630 && sizeof(((T*)0)->x630) == 4, "common field x630"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x634) == 0x634 && sizeof(((T*)0)->x634) == 4, "common field x634"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x638) == 0x638 && sizeof(((T*)0)->x638) == 4, "common field x638"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x63C) == 0x63c && sizeof(((T*)0)->x63C) == 4, "common field x63C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x640) == 0x640 && sizeof(((T*)0)->x640) == 4, "common field x640"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x644) == 0x644 && sizeof(((T*)0)->x644) == 4, "common field x644"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x648) == 0x648 && sizeof(((T*)0)->x648) == 4, "common field x648"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x64C) == 0x64c && sizeof(((T*)0)->x64C) == 4, "common field x64C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x650) == 0x650 && sizeof(((T*)0)->x650) == 4, "common field x650"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x654) == 0x654 && sizeof(((T*)0)->x654) == 4, "common field x654"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x658) == 0x658 && sizeof(((T*)0)->x658) == 4, "common field x658"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x65C) == 0x65c && sizeof(((T*)0)->x65C) == 4, "common field x65C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x660) == 0x660 && sizeof(((T*)0)->x660) == 4, "common field x660"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x664) == 0x664 && sizeof(((T*)0)->x664) == 4, "common field x664"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, pressed_inputs) == 0x668 && sizeof(((T*)0)->pressed_inputs) == 4, "common field pressed_inputs"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, released_inputs) == 0x66c && sizeof(((T*)0)->released_inputs) == 4, "common field released_inputs"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x670) == 0x670 && sizeof(((T*)0)->x670) == 4, "common field x670"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x674) == 0x674 && sizeof(((T*)0)->x674) == 4, "common field x674"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x678) == 0x678 && sizeof(((T*)0)->x678) == 4, "common field x678"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x67C) == 0x67c && sizeof(((T*)0)->x67C) == 4, "common field x67C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x680) == 0x680 && sizeof(((T*)0)->x680) == 4, "common field x680"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x684) == 0x684 && sizeof(((T*)0)->x684) == 4, "common field x684"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x688) == 0x688 && sizeof(((T*)0)->x688) == 4, "common field x688"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x68C) == 0x68c && sizeof(((T*)0)->x68C) == 4, "common field x68C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x690) == 0x690 && sizeof(((T*)0)->x690) == 4, "common field x690"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x694) == 0x694 && sizeof(((T*)0)->x694) == 4, "common field x694"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x698) == 0x698 && sizeof(((T*)0)->x698) == 4, "common field x698"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, warpstarfall_drift_scaling) == 0x69c && sizeof(((T*)0)->warpstarfall_drift_scaling) == 4, "common field warpstarfall_drift_scaling"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, warpstarfall_drift_flat) == 0x6a0 && sizeof(((T*)0)->warpstarfall_drift_flat) == 4, "common field warpstarfall_drift_flat"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, warpstarfall_drift_max) == 0x6a4 && sizeof(((T*)0)->warpstarfall_drift_max) == 4, "common field warpstarfall_drift_max"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6A8) == 0x6a8 && sizeof(((T*)0)->x6A8) == 4, "common field x6A8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6AC) == 0x6ac && sizeof(((T*)0)->x6AC) == 4, "common field x6AC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6B0) == 0x6b0 && sizeof(((T*)0)->x6B0) == 4, "common field x6B0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6B4) == 0x6b4 && sizeof(((T*)0)->x6B4) == 4, "common field x6B4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6B8) == 0x6b8 && sizeof(((T*)0)->x6B8) == 4, "common field x6B8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6BC) == 0x6bc && sizeof(((T*)0)->x6BC) == 4, "common field x6BC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6C0) == 0x6c0 && sizeof(((T*)0)->x6C0) == 4, "common field x6C0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6C4) == 0x6c4 && sizeof(((T*)0)->x6C4) == 4, "common field x6C4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6C8) == 0x6c8 && sizeof(((T*)0)->x6C8) == 4, "common field x6C8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6CC) == 0x6cc && sizeof(((T*)0)->x6CC) == 4, "common field x6CC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6D0) == 0x6d0 && sizeof(((T*)0)->x6D0) == 4, "common field x6D0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6D4) == 0x6d4 && sizeof(((T*)0)->x6D4) == 4, "common field x6D4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6D8[0]) == 0x6d8 && sizeof(((T*)0)->x6D8[0]) == 4, "common field x6D8[0]"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[0].r) == 0x6dc && sizeof(((T*)0)->x6DC_colorsByPlayer[0].r) == 1, "common field x6DC_colorsByPlayer[0].r"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[0].g) == 0x6dd && sizeof(((T*)0)->x6DC_colorsByPlayer[0].g) == 1, "common field x6DC_colorsByPlayer[0].g"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[0].b) == 0x6de && sizeof(((T*)0)->x6DC_colorsByPlayer[0].b) == 1, "common field x6DC_colorsByPlayer[0].b"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[0].a) == 0x6df && sizeof(((T*)0)->x6DC_colorsByPlayer[0].a) == 1, "common field x6DC_colorsByPlayer[0].a"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[1].r) == 0x6e0 && sizeof(((T*)0)->x6DC_colorsByPlayer[1].r) == 1, "common field x6DC_colorsByPlayer[1].r"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[1].g) == 0x6e1 && sizeof(((T*)0)->x6DC_colorsByPlayer[1].g) == 1, "common field x6DC_colorsByPlayer[1].g"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[1].b) == 0x6e2 && sizeof(((T*)0)->x6DC_colorsByPlayer[1].b) == 1, "common field x6DC_colorsByPlayer[1].b"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[1].a) == 0x6e3 && sizeof(((T*)0)->x6DC_colorsByPlayer[1].a) == 1, "common field x6DC_colorsByPlayer[1].a"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[2].r) == 0x6e4 && sizeof(((T*)0)->x6DC_colorsByPlayer[2].r) == 1, "common field x6DC_colorsByPlayer[2].r"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[2].g) == 0x6e5 && sizeof(((T*)0)->x6DC_colorsByPlayer[2].g) == 1, "common field x6DC_colorsByPlayer[2].g"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[2].b) == 0x6e6 && sizeof(((T*)0)->x6DC_colorsByPlayer[2].b) == 1, "common field x6DC_colorsByPlayer[2].b"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[2].a) == 0x6e7 && sizeof(((T*)0)->x6DC_colorsByPlayer[2].a) == 1, "common field x6DC_colorsByPlayer[2].a"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[3].r) == 0x6e8 && sizeof(((T*)0)->x6DC_colorsByPlayer[3].r) == 1, "common field x6DC_colorsByPlayer[3].r"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[3].g) == 0x6e9 && sizeof(((T*)0)->x6DC_colorsByPlayer[3].g) == 1, "common field x6DC_colorsByPlayer[3].g"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[3].b) == 0x6ea && sizeof(((T*)0)->x6DC_colorsByPlayer[3].b) == 1, "common field x6DC_colorsByPlayer[3].b"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6DC_colorsByPlayer[3].a) == 0x6eb && sizeof(((T*)0)->x6DC_colorsByPlayer[3].a) == 1, "common field x6DC_colorsByPlayer[3].a"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6EC[0]) == 0x6ec && sizeof(((T*)0)->x6EC[0]) == 1, "common field x6EC[0]"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6EC[1]) == 0x6ed && sizeof(((T*)0)->x6EC[1]) == 1, "common field x6EC[1]"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6EC[2]) == 0x6ee && sizeof(((T*)0)->x6EC[2]) == 1, "common field x6EC[2]"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6EC[3]) == 0x6ef && sizeof(((T*)0)->x6EC[3]) == 1, "common field x6EC[3]"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, metal_armor) == 0x6f0 && sizeof(((T*)0)->metal_armor) == 4, "common field metal_armor"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6F4_unkDamage) == 0x6f4 && sizeof(((T*)0)->x6F4_unkDamage) == 4, "common field x6F4_unkDamage"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6F8) == 0x6f8 && sizeof(((T*)0)->x6F8) == 4, "common field x6F8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x6FC) == 0x6fc && sizeof(((T*)0)->x6FC) == 4, "common field x6FC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x700) == 0x700 && sizeof(((T*)0)->x700) == 4, "common field x700"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x704) == 0x704 && sizeof(((T*)0)->x704) == 4, "common field x704"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x708) == 0x708 && sizeof(((T*)0)->x708) == 4, "common field x708"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x70C) == 0x70c && sizeof(((T*)0)->x70C) == 4, "common field x70C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x710) == 0x710 && sizeof(((T*)0)->x710) == 4, "common field x710"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x714) == 0x714 && sizeof(((T*)0)->x714) == 4, "common field x714"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, kb_ice_mul) == 0x718 && sizeof(((T*)0)->kb_ice_mul) == 4, "common field kb_ice_mul"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x71C) == 0x71c && sizeof(((T*)0)->x71C) == 4, "common field x71C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x720) == 0x720 && sizeof(((T*)0)->x720) == 4, "common field x720"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x724) == 0x724 && sizeof(((T*)0)->x724) == 4, "common field x724"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x728) == 0x728 && sizeof(((T*)0)->x728) == 4, "common field x728"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x72C) == 0x72c && sizeof(((T*)0)->x72C) == 4, "common field x72C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x730) == 0x730 && sizeof(((T*)0)->x730) == 4, "common field x730"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, leadead_grab_timer_step) == 0x734 && sizeof(((T*)0)->leadead_grab_timer_step) == 4, "common field leadead_grab_timer_step"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, leadead_grab_break_threshold) == 0x738 && sizeof(((T*)0)->leadead_grab_break_threshold) == 4, "common field leadead_grab_break_threshold"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x73C) == 0x73c && sizeof(((T*)0)->x73C) == 4, "common field x73C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x740) == 0x740 && sizeof(((T*)0)->x740) == 4, "common field x740"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x744) == 0x744 && sizeof(((T*)0)->x744) == 4, "common field x744"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x748) == 0x748 && sizeof(((T*)0)->x748) == 4, "common field x748"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x74C) == 0x74c && sizeof(((T*)0)->x74C) == 4, "common field x74C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x750) == 0x750 && sizeof(((T*)0)->x750) == 4, "common field x750"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x754) == 0x754 && sizeof(((T*)0)->x754) == 4, "common field x754"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x758) == 0x758 && sizeof(((T*)0)->x758) == 4, "common field x758"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x75C) == 0x75c && sizeof(((T*)0)->x75C) == 4, "common field x75C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x760) == 0x760 && sizeof(((T*)0)->x760) == 4, "common field x760"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x764) == 0x764 && sizeof(((T*)0)->x764) == 4, "common field x764"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x768) == 0x768 && sizeof(((T*)0)->x768) == 4, "common field x768"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x76C) == 0x76c && sizeof(((T*)0)->x76C) == 4, "common field x76C"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x770) == 0x770 && sizeof(((T*)0)->x770) == 4, "common field x770"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x774) == 0x774 && sizeof(((T*)0)->x774) == 4, "common field x774"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, passive_wall_vel_y_base) == 0x778 && sizeof(((T*)0)->passive_wall_vel_y_base) == 4, "common field passive_wall_vel_y_base"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, damageice_gravity_mult) == 0x77c && sizeof(((T*)0)->damageice_gravity_mult) == 4, "common field damageice_gravity_mult"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, damageice_min_speed) == 0x780 && sizeof(((T*)0)->damageice_min_speed) == 4, "common field damageice_min_speed"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, damageice_speed_mult_on_break) == 0x784 && sizeof(((T*)0)->damageice_speed_mult_on_break) == 4, "common field damageice_speed_mult_on_break"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, damageice_rot_speed_min) == 0x788 && sizeof(((T*)0)->damageice_rot_speed_min) == 4, "common field damageice_rot_speed_min"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, damageice_rot_speed_max) == 0x78c && sizeof(((T*)0)->damageice_rot_speed_max) == 4, "common field damageice_rot_speed_max"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x790_damageice_unk) == 0x790 && sizeof(((T*)0)->x790_damageice_unk) == 4, "common field x790_damageice_unk"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x794_damageice_unk) == 0x794 && sizeof(((T*)0)->x794_damageice_unk) == 4, "common field x794_damageice_unk"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x798_damageice_unk) == 0x798 && sizeof(((T*)0)->x798_damageice_unk) == 4, "common field x798_damageice_unk"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, damageice_dmg_time_reduction_mult) == 0x79c && sizeof(((T*)0)->damageice_dmg_time_reduction_mult) == 4, "common field damageice_dmg_time_reduction_mult"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, damageice_ice_size) == 0x7a0 && sizeof(((T*)0)->damageice_ice_size) == 4, "common field damageice_ice_size"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, damageicejump_escape_time) == 0x7a4 && sizeof(((T*)0)->damageicejump_escape_time) == 4, "common field damageicejump_escape_time"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7A8) == 0x7a8 && sizeof(((T*)0)->x7A8) == 4, "common field x7A8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7AC) == 0x7ac && sizeof(((T*)0)->x7AC) == 4, "common field x7AC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7B0) == 0x7b0 && sizeof(((T*)0)->x7B0) == 4, "common field x7B0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7B4_unkDamage) == 0x7b4 && sizeof(((T*)0)->x7B4_unkDamage) == 4, "common field x7B4_unkDamage"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7B8) == 0x7b8 && sizeof(((T*)0)->x7B8) == 4, "common field x7B8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7BC) == 0x7bc && sizeof(((T*)0)->x7BC) == 4, "common field x7BC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7C0) == 0x7c0 && sizeof(((T*)0)->x7C0) == 4, "common field x7C0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, kb_smashcharge_mul) == 0x7c4 && sizeof(((T*)0)->kb_smashcharge_mul) == 4, "common field kb_smashcharge_mul"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7C8) == 0x7c8 && sizeof(((T*)0)->x7C8) == 4, "common field x7C8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7CC) == 0x7cc && sizeof(((T*)0)->x7CC) == 4, "common field x7CC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7D0) == 0x7d0 && sizeof(((T*)0)->x7D0) == 4, "common field x7D0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, hit_weight_mul) == 0x7d4 && sizeof(((T*)0)->hit_weight_mul) == 4, "common field hit_weight_mul"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7D8.r) == 0x7d8 && sizeof(((T*)0)->x7D8.r) == 1, "common field x7D8.r"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7D8.g) == 0x7d9 && sizeof(((T*)0)->x7D8.g) == 1, "common field x7D8.g"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7D8.b) == 0x7da && sizeof(((T*)0)->x7D8.b) == 1, "common field x7D8.b"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7D8.a) == 0x7db && sizeof(((T*)0)->x7D8.a) == 1, "common field x7D8.a"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7DC) == 0x7dc && sizeof(((T*)0)->x7DC) == 4, "common field x7DC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7E0) == 0x7e0 && sizeof(((T*)0)->x7E0) == 4, "common field x7E0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7E4_scaleZ) == 0x7e4 && sizeof(((T*)0)->x7E4_scaleZ) == 4, "common field x7E4_scaleZ"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, unk_kb_angle_min) == 0x7e8 && sizeof(((T*)0)->unk_kb_angle_min) == 4, "common field unk_kb_angle_min"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, unk_kb_angle_max) == 0x7ec && sizeof(((T*)0)->unk_kb_angle_max) == 4, "common field unk_kb_angle_max"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7F0) == 0x7f0 && sizeof(((T*)0)->x7F0) == 4, "common field x7F0"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7F4) == 0x7f4 && sizeof(((T*)0)->x7F4) == 4, "common field x7F4"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7F8) == 0x7f8 && sizeof(((T*)0)->x7F8) == 4, "common field x7F8"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x7FC) == 0x7fc && sizeof(((T*)0)->x7FC) == 4, "common field x7FC"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x800) == 0x800 && sizeof(((T*)0)->x800) == 4, "common field x800"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x804) == 0x804 && sizeof(((T*)0)->x804) == 4, "common field x804"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x808.x) == 0x808 && sizeof(((T*)0)->x808.x) == 4, "common field x808.x"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x808.y) == 0x80c && sizeof(((T*)0)->x808.y) == 4, "common field x808.y"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x808.z) == 0x810 && sizeof(((T*)0)->x808.z) == 4, "common field x808.z"); \
    MELEE_WEB_COMMON_ASSERT(offsetof(T, x814) == 0x814 && sizeof(((T*)0)->x814) == 4, "common field x814");

#endif
